# Generated by Django 5.0.1 on 2024-02-03 20:30

import blog_bridger_drf.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=50)),
                ('post_body', models.TextField()),
                ('created_at', models.DateField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=models.SET(blog_bridger_drf.models.get_default_user), related_name='post_author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commenter', models.CharField(max_length=225)),
                ('author', models.ForeignKey(on_delete=models.SET(blog_bridger_drf.models.get_default_user), related_name='comment_author', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=models.SET(blog_bridger_drf.models.get_default_user), related_name='post_comments', to='blog_bridger_drf.post')),
            ],
        ),
    ]
