from _typeshed import Incomplete
from ipalib import Updater

logger: Incomplete
register: Incomplete

class update_hcc_enrollment_service(Updater):
    @property
    def service_principal(self): ...
    def add_hcc_enrollment_service(self): ...
    def add_hcc_enrollment_service_keytab(self): ...
    def execute(self, **options): ...
