# Generated by Django 4.2.3 on 2023-09-22 15:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ib_core', '0002_remove_tagbinder_creator_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('creator', models.UUIDField()),
                ('create_date_time_stamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата привязки')),
                ('start_time', models.DateTimeField(verbose_name='Начало активности')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Окончание активности')),
                ('tag_manager', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ib_core.tagmanager')),
            ],
            options={
                'verbose_name': 'Период активности',
                'verbose_name_plural': 'Периоды активности',
                'db_table': 'table_03_activity_periods',
            },
        ),
    ]
