# Youtube Class
from tests.test_create_channel import TestCreateChannel
from tests.test_create_sub_channels import TestCreateSubChannels

from tests.test_create_video import TestCreateVideo 
from tests.test_create_video_sub_channel import TestCreateVideoSubChannel

from tests.test_create_community_post import TestCreateCommunityPost
from tests.test_create_community_post_sub_channel import TestCreateCommunityPostSubChannel

from tests.test_delete_channel import TestDeleteChannel
from tests.test_delete_sub_channel import TestDeleteSubChannel

from tests.test_edit_channel import TestEditChannel
from tests.test_edit_sub_channel import TestEditSubChannel

from tests.test_switch_to_sub_channel import TestSwitchToSubChannel
from tests.test_list_all_channels import TestListAllChannels 

from tests.test_get_my_videos_stats import TestGetMyVideosStats

from tests.test_get_my_channel_handle import TestGetMyChannelHandle
from tests.test_get_my_channel_id import TestGetMyChannelID

from tests.test_get_my_channel_stats import TestGetMyChannelStats

# YoutubeData Class
from tests.test_get_all_video_stats_from_channel import TestGetAllVideoStatsFromChannel
from tests.test_get_channel_id import TestGetChannelID 
from tests.test_get_video_stats import TestGetVideoStats
from tests.test_get_channel_stats import TestGetChannelStats
from tests.test_download_video import TestDownloadVideo
from tests.test_download_thumbnail import TestDownloadThumbnail
