
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-04-05T21:31:09-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "c784b532f526c4789beb28cab28c90ae246b8b91",
 "version": "2024.4.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
