# coding: utf-8

"""
    CryptoAPIs

    Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.

    The version of the OpenAPI document: 2023-04-25
    Contact: developers@cryptoapis.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from com.cryptoapis.rest_apis.sdk.models.tokens_forwarding_success_erc721 import TokensForwardingSuccessErc721

class TestTokensForwardingSuccessErc721(unittest.TestCase):
    """TokensForwardingSuccessErc721 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TokensForwardingSuccessErc721:
        """Test TokensForwardingSuccessErc721
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TokensForwardingSuccessErc721`
        """
        model = TokensForwardingSuccessErc721()
        if include_optional:
            return TokensForwardingSuccessErc721(
                name = 'Wonky Stonks',
                symbol = 'WSTK',
                token_id = '5027',
                contract_address = '0x518ba36f1ca6dfe3bb1b098b8dd0444030e79d9f'
            )
        else:
            return TokensForwardingSuccessErc721(
                name = 'Wonky Stonks',
                symbol = 'WSTK',
                token_id = '5027',
                contract_address = '0x518ba36f1ca6dfe3bb1b098b8dd0444030e79d9f',
        )
        """

    def testTokensForwardingSuccessErc721(self):
        """Test TokensForwardingSuccessErc721"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
