# coding: utf-8

"""
    CryptoAPIs

    Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.

    The version of the OpenAPI document: 2023-04-25
    Contact: developers@cryptoapis.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from com.cryptoapis.rest_apis.sdk.models.list_transactions_by_block_hash_ribsl_vout_inner_script_pub_key import ListTransactionsByBlockHashRIBSLVoutInnerScriptPubKey

class TestListTransactionsByBlockHashRIBSLVoutInnerScriptPubKey(unittest.TestCase):
    """ListTransactionsByBlockHashRIBSLVoutInnerScriptPubKey unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListTransactionsByBlockHashRIBSLVoutInnerScriptPubKey:
        """Test ListTransactionsByBlockHashRIBSLVoutInnerScriptPubKey
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListTransactionsByBlockHashRIBSLVoutInnerScriptPubKey`
        """
        model = ListTransactionsByBlockHashRIBSLVoutInnerScriptPubKey()
        if include_optional:
            return ListTransactionsByBlockHashRIBSLVoutInnerScriptPubKey(
                addresses = [
                    '3LAAY4fp88RsNHkVW5DZJgqUdbMD5rVoqZ'
                    ],
                asm = 'OP_HASH160 ca94af32587de4e5006685ffffc65a818ccd3fbc OP_EQUAL',
                hex = 'a914ca94af32587de4e5006685ffffc65a818ccd3fbc87',
                req_sigs = 2,
                type = 'scripthash'
            )
        else:
            return ListTransactionsByBlockHashRIBSLVoutInnerScriptPubKey(
                addresses = [
                    '3LAAY4fp88RsNHkVW5DZJgqUdbMD5rVoqZ'
                    ],
                asm = 'OP_HASH160 ca94af32587de4e5006685ffffc65a818ccd3fbc OP_EQUAL',
                hex = 'a914ca94af32587de4e5006685ffffc65a818ccd3fbc87',
                type = 'scripthash',
        )
        """

    def testListTransactionsByBlockHashRIBSLVoutInnerScriptPubKey(self):
        """Test ListTransactionsByBlockHashRIBSLVoutInnerScriptPubKey"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
