# coding: utf-8

"""
    CryptoAPIs

    Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.

    The version of the OpenAPI document: 2023-04-25
    Contact: developers@cryptoapis.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from com.cryptoapis.rest_apis.sdk.models.new_unconfirmed_tokens_transactions_rb import NewUnconfirmedTokensTransactionsRB

class TestNewUnconfirmedTokensTransactionsRB(unittest.TestCase):
    """NewUnconfirmedTokensTransactionsRB unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NewUnconfirmedTokensTransactionsRB:
        """Test NewUnconfirmedTokensTransactionsRB
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NewUnconfirmedTokensTransactionsRB`
        """
        model = NewUnconfirmedTokensTransactionsRB()
        if include_optional:
            return NewUnconfirmedTokensTransactionsRB(
                context = 'yourExampleString',
                data = com.cryptoapis.rest_apis.sdk.models.new_unconfirmed_tokens_transactions_rb_data.NewUnconfirmedTokensTransactionsRB_data(
                    item = com.cryptoapis.rest_apis.sdk.models.new_unconfirmed_tokens_transactions_rb_data_item.NewUnconfirmedTokensTransactionsRB_data_item(
                        address = '0x033ef6db9fbd0ee60e2931906b987fe0280471a0', 
                        allow_duplicates = True, 
                        callback_secret_key = 'yourSecretKey', 
                        callback_url = 'https://example.com', ), )
            )
        else:
            return NewUnconfirmedTokensTransactionsRB(
                data = com.cryptoapis.rest_apis.sdk.models.new_unconfirmed_tokens_transactions_rb_data.NewUnconfirmedTokensTransactionsRB_data(
                    item = com.cryptoapis.rest_apis.sdk.models.new_unconfirmed_tokens_transactions_rb_data_item.NewUnconfirmedTokensTransactionsRB_data_item(
                        address = '0x033ef6db9fbd0ee60e2931906b987fe0280471a0', 
                        allow_duplicates = True, 
                        callback_secret_key = 'yourSecretKey', 
                        callback_url = 'https://example.com', ), ),
        )
        """

    def testNewUnconfirmedTokensTransactionsRB(self):
        """Test NewUnconfirmedTokensTransactionsRB"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
