# coding: utf-8

"""
    CryptoAPIs

    Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.

    The version of the OpenAPI document: 2023-04-25
    Contact: developers@cryptoapis.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from com.cryptoapis.rest_apis.sdk.models.create_coins_transaction_request_from_wallet_ri_recipients_inner import CreateCoinsTransactionRequestFromWalletRIRecipientsInner

class TestCreateCoinsTransactionRequestFromWalletRIRecipientsInner(unittest.TestCase):
    """CreateCoinsTransactionRequestFromWalletRIRecipientsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateCoinsTransactionRequestFromWalletRIRecipientsInner:
        """Test CreateCoinsTransactionRequestFromWalletRIRecipientsInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateCoinsTransactionRequestFromWalletRIRecipientsInner`
        """
        model = CreateCoinsTransactionRequestFromWalletRIRecipientsInner()
        if include_optional:
            return CreateCoinsTransactionRequestFromWalletRIRecipientsInner(
                address = 'mmd963W1fECjLyaDCHcioSCZYHkRwjkhtr',
                amount = '0.00123'
            )
        else:
            return CreateCoinsTransactionRequestFromWalletRIRecipientsInner(
                address = 'mmd963W1fECjLyaDCHcioSCZYHkRwjkhtr',
                amount = '0.00123',
        )
        """

    def testCreateCoinsTransactionRequestFromWalletRIRecipientsInner(self):
        """Test CreateCoinsTransactionRequestFromWalletRIRecipientsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
