# coding: utf-8

"""
    CryptoAPIs

    Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.

    The version of the OpenAPI document: 2023-04-25
    Contact: developers@cryptoapis.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from com.cryptoapis.rest_apis.sdk.models.validate_address_e403 import ValidateAddressE403

class TestValidateAddressE403(unittest.TestCase):
    """ValidateAddressE403 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ValidateAddressE403:
        """Test ValidateAddressE403
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ValidateAddressE403`
        """
        model = ValidateAddressE403()
        if include_optional:
            return ValidateAddressE403(
                code = 'feature_mainnets_not_allowed_for_plan',
                message = 'Mainnets access is not available for your current subscription plan, please upgrade your plan to be able to use it.',
                details = [
                    com.cryptoapis.rest_apis.sdk.models.banned_ip_address_details_inner.BannedIpAddress_details_inner(
                        attribute = 'attribute which content caused the error', 
                        message = 'message describing the error', )
                    ]
            )
        else:
            return ValidateAddressE403(
                code = 'feature_mainnets_not_allowed_for_plan',
                message = 'Mainnets access is not available for your current subscription plan, please upgrade your plan to be able to use it.',
        )
        """

    def testValidateAddressE403(self):
        """Test ValidateAddressE403"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
