# coding: utf-8

"""
    CryptoAPIs

    Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.

    The version of the OpenAPI document: 2023-04-25
    Contact: developers@cryptoapis.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from com.cryptoapis.rest_apis.sdk.models.prepare_autxo_based_transaction_from_hd_wallet_x_pub_y_pub_z_pub_ribsd import PrepareAUTXOBasedTransactionFromHDWalletXPubYPubZPubRIBSD

class TestPrepareAUTXOBasedTransactionFromHDWalletXPubYPubZPubRIBSD(unittest.TestCase):
    """PrepareAUTXOBasedTransactionFromHDWalletXPubYPubZPubRIBSD unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PrepareAUTXOBasedTransactionFromHDWalletXPubYPubZPubRIBSD:
        """Test PrepareAUTXOBasedTransactionFromHDWalletXPubYPubZPubRIBSD
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PrepareAUTXOBasedTransactionFromHDWalletXPubYPubZPubRIBSD`
        """
        model = PrepareAUTXOBasedTransactionFromHDWalletXPubYPubZPubRIBSD()
        if include_optional:
            return PrepareAUTXOBasedTransactionFromHDWalletXPubYPubZPubRIBSD(
                vin = [
                    com.cryptoapis.rest_apis.sdk.models.prepare_autxo_based_transaction_from_hd_wallet_x_pub_y_pub_z_pub_ribsd_vin_inner.PrepareAUTXO_BasedTransactionFromHDWalletXPubYPubZPubRIBSD_vin_inner(
                        address = 'neBSn1hmh62R5gzdwbBf4z8nEVrKtqJkpx', 
                        change = 1, 
                        derivation_index = 100, 
                        output_index = 1, 
                        satoshis = 100000000, 
                        script = '76a9146d8ea0455263c2589f08ef450dc3759cebd671ba88ac', 
                        sighash = '77ce11bc9a94a17c2361cc3b9d91e871a468df3a7c4d588c82ed790f37fbe2be', 
                        transaction_id = '26d90b7d57fd5590a6296360744dc6b21c3c938de3fd5594be9f6f9c9cffa35f', )
                    ],
                vout = [
                    com.cryptoapis.rest_apis.sdk.models.prepare_autxo_based_transaction_from_hd_wallet_x_pub_y_pub_z_pub_ribsd_vout_inner.PrepareAUTXO_BasedTransactionFromHDWalletXPubYPubZPubRIBSD_vout_inner(
                        address = 'niDY7k4YsHPpLLF3rWwzmDpsu52j2UTgqS', 
                        satoshis = 100000000, 
                        script = '76a9146d8ea0455263c2589f08ef450dc3759cebd671ba88ac', )
                    ]
            )
        else:
            return PrepareAUTXOBasedTransactionFromHDWalletXPubYPubZPubRIBSD(
                vin = [
                    com.cryptoapis.rest_apis.sdk.models.prepare_autxo_based_transaction_from_hd_wallet_x_pub_y_pub_z_pub_ribsd_vin_inner.PrepareAUTXO_BasedTransactionFromHDWalletXPubYPubZPubRIBSD_vin_inner(
                        address = 'neBSn1hmh62R5gzdwbBf4z8nEVrKtqJkpx', 
                        change = 1, 
                        derivation_index = 100, 
                        output_index = 1, 
                        satoshis = 100000000, 
                        script = '76a9146d8ea0455263c2589f08ef450dc3759cebd671ba88ac', 
                        sighash = '77ce11bc9a94a17c2361cc3b9d91e871a468df3a7c4d588c82ed790f37fbe2be', 
                        transaction_id = '26d90b7d57fd5590a6296360744dc6b21c3c938de3fd5594be9f6f9c9cffa35f', )
                    ],
                vout = [
                    com.cryptoapis.rest_apis.sdk.models.prepare_autxo_based_transaction_from_hd_wallet_x_pub_y_pub_z_pub_ribsd_vout_inner.PrepareAUTXO_BasedTransactionFromHDWalletXPubYPubZPubRIBSD_vout_inner(
                        address = 'niDY7k4YsHPpLLF3rWwzmDpsu52j2UTgqS', 
                        satoshis = 100000000, 
                        script = '76a9146d8ea0455263c2589f08ef450dc3759cebd671ba88ac', )
                    ],
        )
        """

    def testPrepareAUTXOBasedTransactionFromHDWalletXPubYPubZPubRIBSD(self):
        """Test PrepareAUTXOBasedTransactionFromHDWalletXPubYPubZPubRIBSD"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
