# coding: utf-8

"""
    CryptoAPIs

    Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.

    The version of the OpenAPI document: 2023-04-25
    Contact: developers@cryptoapis.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from com.cryptoapis.rest_apis.sdk.models.new_block_r_data import NewBlockRData

class TestNewBlockRData(unittest.TestCase):
    """NewBlockRData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NewBlockRData:
        """Test NewBlockRData
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NewBlockRData`
        """
        model = NewBlockRData()
        if include_optional:
            return NewBlockRData(
                item = com.cryptoapis.rest_apis.sdk.models.new_block_ri.NewBlockRI(
                    callback_secret_key = 'yourSecretKey', 
                    callback_url = 'https://yourURL.com', 
                    created_timestamp = 1611238648, 
                    is_active = True, 
                    reference_id = '4c530a43-5602-41d9-bc69-156a0372f9aa', )
            )
        else:
            return NewBlockRData(
                item = com.cryptoapis.rest_apis.sdk.models.new_block_ri.NewBlockRI(
                    callback_secret_key = 'yourSecretKey', 
                    callback_url = 'https://yourURL.com', 
                    created_timestamp = 1611238648, 
                    is_active = True, 
                    reference_id = '4c530a43-5602-41d9-bc69-156a0372f9aa', ),
        )
        """

    def testNewBlockRData(self):
        """Test NewBlockRData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
