# coding: utf-8

"""
    CryptoAPIs

    Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.

    The version of the OpenAPI document: 2023-04-25
    Contact: developers@cryptoapis.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from com.cryptoapis.rest_apis.sdk.models.mined_transaction_rb_data_item import MinedTransactionRBDataItem

class TestMinedTransactionRBDataItem(unittest.TestCase):
    """MinedTransactionRBDataItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MinedTransactionRBDataItem:
        """Test MinedTransactionRBDataItem
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MinedTransactionRBDataItem`
        """
        model = MinedTransactionRBDataItem()
        if include_optional:
            return MinedTransactionRBDataItem(
                allow_duplicates = False,
                callback_secret_key = 'yourSecretKey',
                callback_url = 'https://example.com',
                transaction_id = 'df2690ff97e72c1f8b0f2102a8cb5c1d0fa8fb8754d543c9bc0edc4d4bc34bfc'
            )
        else:
            return MinedTransactionRBDataItem(
                callback_url = 'https://example.com',
                transaction_id = 'df2690ff97e72c1f8b0f2102a8cb5c1d0fa8fb8754d543c9bc0edc4d4bc34bfc',
        )
        """

    def testMinedTransactionRBDataItem(self):
        """Test MinedTransactionRBDataItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
