# coding: utf-8

"""
    CryptoAPIs

    Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.

    The version of the OpenAPI document: 2023-04-25
    Contact: developers@cryptoapis.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from com.cryptoapis.rest_apis.sdk.models.get_asset_details_by_asset_symbol400_response import GetAssetDetailsByAssetSymbol400Response

class TestGetAssetDetailsByAssetSymbol400Response(unittest.TestCase):
    """GetAssetDetailsByAssetSymbol400Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetAssetDetailsByAssetSymbol400Response:
        """Test GetAssetDetailsByAssetSymbol400Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetAssetDetailsByAssetSymbol400Response`
        """
        model = GetAssetDetailsByAssetSymbol400Response()
        if include_optional:
            return GetAssetDetailsByAssetSymbol400Response(
                api_version = '2023-04-25',
                request_id = '601c1710034ed6d407996b30',
                context = 'yourExampleString',
                error = com.cryptoapis.rest_apis.sdk.models.get_asset_details_by_asset_symbol_e400.GetAssetDetailsByAssetSymbolE400()
            )
        else:
            return GetAssetDetailsByAssetSymbol400Response(
                api_version = '2023-04-25',
                request_id = '601c1710034ed6d407996b30',
                error = com.cryptoapis.rest_apis.sdk.models.get_asset_details_by_asset_symbol_e400.GetAssetDetailsByAssetSymbolE400(),
        )
        """

    def testGetAssetDetailsByAssetSymbol400Response(self):
        """Test GetAssetDetailsByAssetSymbol400Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
