# coding: utf-8

"""
    CryptoAPIs

    Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.

    The version of the OpenAPI document: 2023-04-25
    Contact: developers@cryptoapis.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from com.cryptoapis.rest_apis.sdk.models.get_transaction_details_by_transaction_idribsbsc_gas_price import GetTransactionDetailsByTransactionIDRIBSBSCGasPrice

class TestGetTransactionDetailsByTransactionIDRIBSBSCGasPrice(unittest.TestCase):
    """GetTransactionDetailsByTransactionIDRIBSBSCGasPrice unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetTransactionDetailsByTransactionIDRIBSBSCGasPrice:
        """Test GetTransactionDetailsByTransactionIDRIBSBSCGasPrice
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetTransactionDetailsByTransactionIDRIBSBSCGasPrice`
        """
        model = GetTransactionDetailsByTransactionIDRIBSBSCGasPrice()
        if include_optional:
            return GetTransactionDetailsByTransactionIDRIBSBSCGasPrice(
                amount = '20000000000',
                unit = 'BNB'
            )
        else:
            return GetTransactionDetailsByTransactionIDRIBSBSCGasPrice(
                amount = '20000000000',
                unit = 'BNB',
        )
        """

    def testGetTransactionDetailsByTransactionIDRIBSBSCGasPrice(self):
        """Test GetTransactionDetailsByTransactionIDRIBSBSCGasPrice"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
