# coding: utf-8

"""
    CryptoAPIs

    Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.

    The version of the OpenAPI document: 2023-04-25
    Contact: developers@cryptoapis.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from com.cryptoapis.rest_apis.sdk.models.create_fungible_tokens_transaction_request_from_address_ri_recipients_inner import CreateFungibleTokensTransactionRequestFromAddressRIRecipientsInner

class TestCreateFungibleTokensTransactionRequestFromAddressRIRecipientsInner(unittest.TestCase):
    """CreateFungibleTokensTransactionRequestFromAddressRIRecipientsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateFungibleTokensTransactionRequestFromAddressRIRecipientsInner:
        """Test CreateFungibleTokensTransactionRequestFromAddressRIRecipientsInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateFungibleTokensTransactionRequestFromAddressRIRecipientsInner`
        """
        model = CreateFungibleTokensTransactionRequestFromAddressRIRecipientsInner()
        if include_optional:
            return CreateFungibleTokensTransactionRequestFromAddressRIRecipientsInner(
                address = '0xc6d46aba0c6e2eb6358c4e24804158cc4d847922',
                amount = '1'
            )
        else:
            return CreateFungibleTokensTransactionRequestFromAddressRIRecipientsInner(
                address = '0xc6d46aba0c6e2eb6358c4e24804158cc4d847922',
                amount = '1',
        )
        """

    def testCreateFungibleTokensTransactionRequestFromAddressRIRecipientsInner(self):
        """Test CreateFungibleTokensTransactionRequestFromAddressRIRecipientsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
