# coding: utf-8

"""
    CryptoAPIs

    Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.

    The version of the OpenAPI document: 2023-04-25
    Contact: developers@cryptoapis.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from com.cryptoapis.rest_apis.sdk.models.get_address_balance_r_data import GetAddressBalanceRData

class TestGetAddressBalanceRData(unittest.TestCase):
    """GetAddressBalanceRData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetAddressBalanceRData:
        """Test GetAddressBalanceRData
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetAddressBalanceRData`
        """
        model = GetAddressBalanceRData()
        if include_optional:
            return GetAddressBalanceRData(
                item = com.cryptoapis.rest_apis.sdk.models.get_address_balance_ri.GetAddressBalanceRI(
                    confirmed_balance = com.cryptoapis.rest_apis.sdk.models.get_address_balance_ri_confirmed_balance.GetAddressBalanceRI_confirmedBalance(
                        amount = '3.462515', 
                        unit = 'ETH', ), )
            )
        else:
            return GetAddressBalanceRData(
                item = com.cryptoapis.rest_apis.sdk.models.get_address_balance_ri.GetAddressBalanceRI(
                    confirmed_balance = com.cryptoapis.rest_apis.sdk.models.get_address_balance_ri_confirmed_balance.GetAddressBalanceRI_confirmedBalance(
                        amount = '3.462515', 
                        unit = 'ETH', ), ),
        )
        """

    def testGetAddressBalanceRData(self):
        """Test GetAddressBalanceRData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
