# coding: utf-8

"""
    CryptoAPIs

    Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.

    The version of the OpenAPI document: 2023-04-25
    Contact: developers@cryptoapis.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from com.cryptoapis.rest_apis.sdk.models.create_automatic_tokens_forwarding_r import CreateAutomaticTokensForwardingR

class TestCreateAutomaticTokensForwardingR(unittest.TestCase):
    """CreateAutomaticTokensForwardingR unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateAutomaticTokensForwardingR:
        """Test CreateAutomaticTokensForwardingR
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateAutomaticTokensForwardingR`
        """
        model = CreateAutomaticTokensForwardingR()
        if include_optional:
            return CreateAutomaticTokensForwardingR(
                api_version = '2023-04-25',
                request_id = '601c1710034ed6d407996b30',
                context = 'yourExampleString',
                data = com.cryptoapis.rest_apis.sdk.models.create_automatic_tokens_forwarding_r_data.CreateAutomaticTokensForwardingR_data(
                    item = com.cryptoapis.rest_apis.sdk.models.create_automatic_tokens_forwarding_ri.CreateAutomaticTokensForwardingRI(
                        callback_url = 'https://example.com', 
                        confirmations_count = 2, 
                        created_timestamp = 1611238648, 
                        fee_address = 'mojjR51gMXLJ4B3SBPhEXXRFDX7U5UWXNQ', 
                        fee_priority = 'standard', 
                        from_address = 'ms4KNsbNpoU8g424pzmEjbkFbfAHae1msB', 
                        minimum_transfer_amount = '0.5', 
                        reference_id = '6017dd02a309213863be9e55', 
                        to_address = 'tb1q54j7qcu7kgsrx87yn0r9zjdvsxrnvxg4qua2z6', 
                        token_data = com.cryptoapis.rest_apis.sdk.models.create_automatic_tokens_forwarding_rits.CreateAutomaticTokensForwardingRITS(), ), )
            )
        else:
            return CreateAutomaticTokensForwardingR(
                api_version = '2023-04-25',
                request_id = '601c1710034ed6d407996b30',
                data = com.cryptoapis.rest_apis.sdk.models.create_automatic_tokens_forwarding_r_data.CreateAutomaticTokensForwardingR_data(
                    item = com.cryptoapis.rest_apis.sdk.models.create_automatic_tokens_forwarding_ri.CreateAutomaticTokensForwardingRI(
                        callback_url = 'https://example.com', 
                        confirmations_count = 2, 
                        created_timestamp = 1611238648, 
                        fee_address = 'mojjR51gMXLJ4B3SBPhEXXRFDX7U5UWXNQ', 
                        fee_priority = 'standard', 
                        from_address = 'ms4KNsbNpoU8g424pzmEjbkFbfAHae1msB', 
                        minimum_transfer_amount = '0.5', 
                        reference_id = '6017dd02a309213863be9e55', 
                        to_address = 'tb1q54j7qcu7kgsrx87yn0r9zjdvsxrnvxg4qua2z6', 
                        token_data = com.cryptoapis.rest_apis.sdk.models.create_automatic_tokens_forwarding_rits.CreateAutomaticTokensForwardingRITS(), ), ),
        )
        """

    def testCreateAutomaticTokensForwardingR(self):
        """Test CreateAutomaticTokensForwardingR"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
