# coding: utf-8

"""
    CryptoAPIs

    Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.

    The version of the OpenAPI document: 2023-04-25
    Contact: developers@cryptoapis.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from com.cryptoapis.rest_apis.sdk.models.get_hd_wallet_x_pub_y_pub_z_pub_details_e400 import GetHDWalletXPubYPubZPubDetailsE400

class TestGetHDWalletXPubYPubZPubDetailsE400(unittest.TestCase):
    """GetHDWalletXPubYPubZPubDetailsE400 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetHDWalletXPubYPubZPubDetailsE400:
        """Test GetHDWalletXPubYPubZPubDetailsE400
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetHDWalletXPubYPubZPubDetailsE400`
        """
        model = GetHDWalletXPubYPubZPubDetailsE400()
        if include_optional:
            return GetHDWalletXPubYPubZPubDetailsE400(
                code = 'xpub_not_synced',
                message = 'This xPub is not yet synced, please first use endpoint “Sync HD (xPub, yPub, zPub) wallet” to synchronize it.',
                details = [
                    com.cryptoapis.rest_apis.sdk.models.banned_ip_address_details_inner.BannedIpAddress_details_inner(
                        attribute = 'attribute which content caused the error', 
                        message = 'message describing the error', )
                    ]
            )
        else:
            return GetHDWalletXPubYPubZPubDetailsE400(
                code = 'xpub_not_synced',
                message = 'This xPub is not yet synced, please first use endpoint “Sync HD (xPub, yPub, zPub) wallet” to synchronize it.',
        )
        """

    def testGetHDWalletXPubYPubZPubDetailsE400(self):
        """Test GetHDWalletXPubYPubZPubDetailsE400"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
