# coding: utf-8

"""
    CryptoAPIs

    Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.

    The version of the OpenAPI document: 2023-04-25
    Contact: developers@cryptoapis.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from com.cryptoapis.rest_apis.sdk.models.list_supported_tokens_ri import ListSupportedTokensRI

class TestListSupportedTokensRI(unittest.TestCase):
    """ListSupportedTokensRI unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListSupportedTokensRI:
        """Test ListSupportedTokensRI
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListSupportedTokensRI`
        """
        model = ListSupportedTokensRI()
        if include_optional:
            return ListSupportedTokensRI(
                decimals = 6,
                identifier = '0xdac17f958d2ee523a2206206994597c13d831ec7',
                name = 'Tether',
                symbol = 'USDT',
                type = 'ERC-20'
            )
        else:
            return ListSupportedTokensRI(
                decimals = 6,
                identifier = '0xdac17f958d2ee523a2206206994597c13d831ec7',
                name = 'Tether',
                symbol = 'USDT',
                type = 'ERC-20',
        )
        """

    def testListSupportedTokensRI(self):
        """Test ListSupportedTokensRI"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
