# coding: utf-8

"""
    CryptoAPIs

    Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.

    The version of the OpenAPI document: 2023-04-25
    Contact: developers@cryptoapis.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from com.cryptoapis.rest_apis.sdk.models.list_confirmed_transactions_by_address_ribsb_vout_inner import ListConfirmedTransactionsByAddressRIBSBVoutInner

class TestListConfirmedTransactionsByAddressRIBSBVoutInner(unittest.TestCase):
    """ListConfirmedTransactionsByAddressRIBSBVoutInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListConfirmedTransactionsByAddressRIBSBVoutInner:
        """Test ListConfirmedTransactionsByAddressRIBSBVoutInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListConfirmedTransactionsByAddressRIBSBVoutInner`
        """
        model = ListConfirmedTransactionsByAddressRIBSBVoutInner()
        if include_optional:
            return ListConfirmedTransactionsByAddressRIBSBVoutInner(
                is_spent = True,
                script_pub_key = com.cryptoapis.rest_apis.sdk.models.list_confirmed_transactions_by_address_ribsb_vout_inner_script_pub_key.ListConfirmedTransactionsByAddressRIBSB_vout_inner_scriptPubKey(
                    addresses = [
                        '2N5PcdirZUzKF9bWuGdugNuzcQrCbBudxv1'
                        ], 
                    asm = 'OP_HASH160 ca94af32587de4e5006685ffffc65a818ccd3fbc OP_EQUAL', 
                    hex = 'a914507a5bd8cac1d9efdf4c0a4bfacb3e0abb4f8d1587', 
                    req_sigs = 1, 
                    type = 'scripthash', ),
                value = '0.000144'
            )
        else:
            return ListConfirmedTransactionsByAddressRIBSBVoutInner(
                is_spent = True,
                script_pub_key = com.cryptoapis.rest_apis.sdk.models.list_confirmed_transactions_by_address_ribsb_vout_inner_script_pub_key.ListConfirmedTransactionsByAddressRIBSB_vout_inner_scriptPubKey(
                    addresses = [
                        '2N5PcdirZUzKF9bWuGdugNuzcQrCbBudxv1'
                        ], 
                    asm = 'OP_HASH160 ca94af32587de4e5006685ffffc65a818ccd3fbc OP_EQUAL', 
                    hex = 'a914507a5bd8cac1d9efdf4c0a4bfacb3e0abb4f8d1587', 
                    req_sigs = 1, 
                    type = 'scripthash', ),
                value = '0.000144',
        )
        """

    def testListConfirmedTransactionsByAddressRIBSBVoutInner(self):
        """Test ListConfirmedTransactionsByAddressRIBSBVoutInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
