# coding: utf-8

"""
    CryptoAPIs

    Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.

    The version of the OpenAPI document: 2023-04-25
    Contact: developers@cryptoapis.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from com.cryptoapis.rest_apis.sdk.models.get_block_details_by_block_height_ribs import GetBlockDetailsByBlockHeightRIBS

class TestGetBlockDetailsByBlockHeightRIBS(unittest.TestCase):
    """GetBlockDetailsByBlockHeightRIBS unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetBlockDetailsByBlockHeightRIBS:
        """Test GetBlockDetailsByBlockHeightRIBS
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetBlockDetailsByBlockHeightRIBS`
        """
        model = GetBlockDetailsByBlockHeightRIBS()
        if include_optional:
            return GetBlockDetailsByBlockHeightRIBS(
                bits = '524517883',
                chainwork = '000000000000000000000000000000000000000000000000000000262b072797',
                difficulty = '',
                merkle_root = '961113ae943a3abf76da307cf881c4c6b6c13efb27fb67f02c9cdb46029848e8',
                nonce = '1535290446',
                size = 3892,
                stripped_size = 930838,
                version = 4,
                version_hex = '30000000',
                weight = 2238302,
                extra_data = '0xd983010203844765746887676f312e342e328777696e646f7773',
                gas_limit = '3141592',
                gas_used = '21000',
                mined_in_seconds = 5,
                sha3_uncles = '0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347',
                total_difficulty = '20104747399762079739558',
                base_fee = '0.00001',
                base_reserve = '0.5',
                failed_transactions = 12,
                protocol_version = '19',
                total_coins = '105443902087.3472865'
            )
        else:
            return GetBlockDetailsByBlockHeightRIBS(
                bits = '524517883',
                chainwork = '000000000000000000000000000000000000000000000000000000262b072797',
                merkle_root = '961113ae943a3abf76da307cf881c4c6b6c13efb27fb67f02c9cdb46029848e8',
                nonce = '1535290446',
                size = 3892,
                stripped_size = 930838,
                version = 4,
                version_hex = '30000000',
                weight = 2238302,
                extra_data = '0xd983010203844765746887676f312e342e328777696e646f7773',
                gas_limit = '3141592',
                gas_used = '21000',
                mined_in_seconds = 5,
                sha3_uncles = '0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347',
                total_difficulty = '20104747399762079739558',
                base_fee = '0.00001',
                base_reserve = '0.5',
                failed_transactions = 12,
                protocol_version = '19',
                total_coins = '105443902087.3472865',
        )
        """

    def testGetBlockDetailsByBlockHeightRIBS(self):
        """Test GetBlockDetailsByBlockHeightRIBS"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
