# coding: utf-8

"""
    CryptoAPIs

    Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.

    The version of the OpenAPI document: 2023-04-25
    Contact: developers@cryptoapis.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from com.cryptoapis.rest_apis.sdk.models.get_block_details_by_block_height_from_callback_ribsbc import GetBlockDetailsByBlockHeightFromCallbackRIBSBC

class TestGetBlockDetailsByBlockHeightFromCallbackRIBSBC(unittest.TestCase):
    """GetBlockDetailsByBlockHeightFromCallbackRIBSBC unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetBlockDetailsByBlockHeightFromCallbackRIBSBC:
        """Test GetBlockDetailsByBlockHeightFromCallbackRIBSBC
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetBlockDetailsByBlockHeightFromCallbackRIBSBC`
        """
        model = GetBlockDetailsByBlockHeightFromCallbackRIBSBC()
        if include_optional:
            return GetBlockDetailsByBlockHeightFromCallbackRIBSBC(
                bits = '386689514',
                chainwork = '0000000000000000000000000000000000000000015dc8754d8bfaedfffbb3bd',
                difficulty = '5399792.015244232',
                merkle_root = '543872ba53c13183f951d76dd5933f98900a1bf9b3eef716857dfcc3c0534dfb',
                nonce = 1923421957,
                size = 191,
                version = 545259520,
                version_hex = '20000000'
            )
        else:
            return GetBlockDetailsByBlockHeightFromCallbackRIBSBC(
                bits = '386689514',
                chainwork = '0000000000000000000000000000000000000000015dc8754d8bfaedfffbb3bd',
                difficulty = '5399792.015244232',
                merkle_root = '543872ba53c13183f951d76dd5933f98900a1bf9b3eef716857dfcc3c0534dfb',
                nonce = 1923421957,
                size = 191,
                version = 545259520,
                version_hex = '20000000',
        )
        """

    def testGetBlockDetailsByBlockHeightFromCallbackRIBSBC(self):
        """Test GetBlockDetailsByBlockHeightFromCallbackRIBSBC"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
