# coding: utf-8

"""
    CryptoAPIs

    Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.

    The version of the OpenAPI document: 2023-04-25
    Contact: developers@cryptoapis.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from com.cryptoapis.rest_apis.sdk.models.prepare_autxo_based_transaction_from_hd_wallet_x_pub_y_pub_z_pub_ribsd2_vout_inner import PrepareAUTXOBasedTransactionFromHDWalletXPubYPubZPubRIBSD2VoutInner

class TestPrepareAUTXOBasedTransactionFromHDWalletXPubYPubZPubRIBSD2VoutInner(unittest.TestCase):
    """PrepareAUTXOBasedTransactionFromHDWalletXPubYPubZPubRIBSD2VoutInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PrepareAUTXOBasedTransactionFromHDWalletXPubYPubZPubRIBSD2VoutInner:
        """Test PrepareAUTXOBasedTransactionFromHDWalletXPubYPubZPubRIBSD2VoutInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PrepareAUTXOBasedTransactionFromHDWalletXPubYPubZPubRIBSD2VoutInner`
        """
        model = PrepareAUTXOBasedTransactionFromHDWalletXPubYPubZPubRIBSD2VoutInner()
        if include_optional:
            return PrepareAUTXOBasedTransactionFromHDWalletXPubYPubZPubRIBSD2VoutInner(
                address = 'yiEkTwAaWxawCF6PA1f1zamxYdYAyooTM1',
                satoshis = 912296178,
                script = '76a914f06f64804efee250cb9d3702d82203eb48c5a5ae88ac'
            )
        else:
            return PrepareAUTXOBasedTransactionFromHDWalletXPubYPubZPubRIBSD2VoutInner(
                address = 'yiEkTwAaWxawCF6PA1f1zamxYdYAyooTM1',
                satoshis = 912296178,
                script = '76a914f06f64804efee250cb9d3702d82203eb48c5a5ae88ac',
        )
        """

    def testPrepareAUTXOBasedTransactionFromHDWalletXPubYPubZPubRIBSD2VoutInner(self):
        """Test PrepareAUTXOBasedTransactionFromHDWalletXPubYPubZPubRIBSD2VoutInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
