# coding: utf-8

"""
    CryptoAPIs

    Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.

    The version of the OpenAPI document: 2023-04-25
    Contact: developers@cryptoapis.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from com.cryptoapis.rest_apis.sdk.models.list_unconfirmed_transactions_by_address_ribsd2_vout_inner import ListUnconfirmedTransactionsByAddressRIBSD2VoutInner

class TestListUnconfirmedTransactionsByAddressRIBSD2VoutInner(unittest.TestCase):
    """ListUnconfirmedTransactionsByAddressRIBSD2VoutInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListUnconfirmedTransactionsByAddressRIBSD2VoutInner:
        """Test ListUnconfirmedTransactionsByAddressRIBSD2VoutInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListUnconfirmedTransactionsByAddressRIBSD2VoutInner`
        """
        model = ListUnconfirmedTransactionsByAddressRIBSD2VoutInner()
        if include_optional:
            return ListUnconfirmedTransactionsByAddressRIBSD2VoutInner(
                is_spent = False,
                script_pub_key = com.cryptoapis.rest_apis.sdk.models.list_confirmed_transactions_by_address_ribsd2_vout_inner_script_pub_key.ListConfirmedTransactionsByAddressRIBSD2_vout_inner_scriptPubKey(
                    addresses = [
                        'yP8A3cbdxRtLRduy5mXDsBnJtMzHWs6ZXr'
                        ], 
                    asm = 'OP_DUP OP_HASH160 1ec5c66e9789c655ae068d35088b4073345fe0b0 OP_EQUALVERIFY OP_CHECKSIG', 
                    hex = '76a9141ec5c66e9789c655ae068d35088b4073345fe0b088ac', 
                    req_sigs = 1, 
                    type = 'scripthash', ),
                value = '7.76020409'
            )
        else:
            return ListUnconfirmedTransactionsByAddressRIBSD2VoutInner(
                is_spent = False,
                script_pub_key = com.cryptoapis.rest_apis.sdk.models.list_confirmed_transactions_by_address_ribsd2_vout_inner_script_pub_key.ListConfirmedTransactionsByAddressRIBSD2_vout_inner_scriptPubKey(
                    addresses = [
                        'yP8A3cbdxRtLRduy5mXDsBnJtMzHWs6ZXr'
                        ], 
                    asm = 'OP_DUP OP_HASH160 1ec5c66e9789c655ae068d35088b4073345fe0b0 OP_EQUALVERIFY OP_CHECKSIG', 
                    hex = '76a9141ec5c66e9789c655ae068d35088b4073345fe0b088ac', 
                    req_sigs = 1, 
                    type = 'scripthash', ),
                value = '7.76020409',
        )
        """

    def testListUnconfirmedTransactionsByAddressRIBSD2VoutInner(self):
        """Test ListUnconfirmedTransactionsByAddressRIBSD2VoutInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
