# coding: utf-8

"""
    CryptoAPIs

    Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.

    The version of the OpenAPI document: 2023-04-25
    Contact: developers@cryptoapis.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from com.cryptoapis.rest_apis.sdk.models.prepare_transaction_from_address_ribse import PrepareTransactionFromAddressRIBSE

class TestPrepareTransactionFromAddressRIBSE(unittest.TestCase):
    """PrepareTransactionFromAddressRIBSE unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PrepareTransactionFromAddressRIBSE:
        """Test PrepareTransactionFromAddressRIBSE
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PrepareTransactionFromAddressRIBSE`
        """
        model = PrepareTransactionFromAddressRIBSE()
        if include_optional:
            return PrepareTransactionFromAddressRIBSE(
                fee = com.cryptoapis.rest_apis.sdk.models.prepare_transaction_from_address_ribsbsc_fee.PrepareTransactionFromAddressRIBSBSC_fee(
                    gas_limit = '21220', 
                    gas_price = '47125353', ),
                transaction_type = 'access-list-transaction',
                unit = 'WEI'
            )
        else:
            return PrepareTransactionFromAddressRIBSE(
                fee = com.cryptoapis.rest_apis.sdk.models.prepare_transaction_from_address_ribsbsc_fee.PrepareTransactionFromAddressRIBSBSC_fee(
                    gas_limit = '21220', 
                    gas_price = '47125353', ),
                transaction_type = 'access-list-transaction',
                unit = 'WEI',
        )
        """

    def testPrepareTransactionFromAddressRIBSE(self):
        """Test PrepareTransactionFromAddressRIBSE"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
