# coding: utf-8

"""
    CryptoAPIs

    Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.

    The version of the OpenAPI document: 2023-04-25
    Contact: developers@cryptoapis.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from com.cryptoapis.rest_apis.sdk.models.prepare_a_transaction_from_an_address_in_hd_wallet_x_pub_y_pub_z_pub_ribse_fee import PrepareATransactionFromAnAddressInHDWalletXPubYPubZPubRIBSEFee

class TestPrepareATransactionFromAnAddressInHDWalletXPubYPubZPubRIBSEFee(unittest.TestCase):
    """PrepareATransactionFromAnAddressInHDWalletXPubYPubZPubRIBSEFee unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PrepareATransactionFromAnAddressInHDWalletXPubYPubZPubRIBSEFee:
        """Test PrepareATransactionFromAnAddressInHDWalletXPubYPubZPubRIBSEFee
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PrepareATransactionFromAnAddressInHDWalletXPubYPubZPubRIBSEFee`
        """
        model = PrepareATransactionFromAnAddressInHDWalletXPubYPubZPubRIBSEFee()
        if include_optional:
            return PrepareATransactionFromAnAddressInHDWalletXPubYPubZPubRIBSEFee(
                gas_limit = '552020',
                gas_price = '2500000007',
                max_fee_per_gas = '2000000008',
                max_priority_fee_per_gas = '2000000000'
            )
        else:
            return PrepareATransactionFromAnAddressInHDWalletXPubYPubZPubRIBSEFee(
                gas_limit = '552020',
                gas_price = '2500000007',
                max_fee_per_gas = '2000000008',
                max_priority_fee_per_gas = '2000000000',
        )
        """

    def testPrepareATransactionFromAnAddressInHDWalletXPubYPubZPubRIBSEFee(self):
        """Test PrepareATransactionFromAnAddressInHDWalletXPubYPubZPubRIBSEFee"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
