# coding: utf-8

"""
    CryptoAPIs

    Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.

    The version of the OpenAPI document: 2023-04-25
    Contact: developers@cryptoapis.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from com.cryptoapis.rest_apis.sdk.models.list_transactions_by_block_hash_ribsb_vout_inner_script_pub_key import ListTransactionsByBlockHashRIBSBVoutInnerScriptPubKey

class TestListTransactionsByBlockHashRIBSBVoutInnerScriptPubKey(unittest.TestCase):
    """ListTransactionsByBlockHashRIBSBVoutInnerScriptPubKey unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListTransactionsByBlockHashRIBSBVoutInnerScriptPubKey:
        """Test ListTransactionsByBlockHashRIBSBVoutInnerScriptPubKey
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListTransactionsByBlockHashRIBSBVoutInnerScriptPubKey`
        """
        model = ListTransactionsByBlockHashRIBSBVoutInnerScriptPubKey()
        if include_optional:
            return ListTransactionsByBlockHashRIBSBVoutInnerScriptPubKey(
                addresses = [
                    '2N5PcdirZUzKF9bWuGdugNuzcQrCbBudxv1'
                    ],
                asm = 'OP_HASH160 507a5bd8cac1d9efdf4c0a4bfacb3e0abb4f8d15 OP_EQUAL',
                hex = 'a914507a5bd8cac1d9efdf4c0a4bfacb3e0abb4f8d1587',
                req_sigs = 1,
                type = 'scripthash'
            )
        else:
            return ListTransactionsByBlockHashRIBSBVoutInnerScriptPubKey(
                addresses = [
                    '2N5PcdirZUzKF9bWuGdugNuzcQrCbBudxv1'
                    ],
                asm = 'OP_HASH160 507a5bd8cac1d9efdf4c0a4bfacb3e0abb4f8d15 OP_EQUAL',
                hex = 'a914507a5bd8cac1d9efdf4c0a4bfacb3e0abb4f8d1587',
                type = 'scripthash',
        )
        """

    def testListTransactionsByBlockHashRIBSBVoutInnerScriptPubKey(self):
        """Test ListTransactionsByBlockHashRIBSBVoutInnerScriptPubKey"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
