# coding: utf-8

"""
    CryptoAPIs

    Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.

    The version of the OpenAPI document: 2023-04-25
    Contact: developers@cryptoapis.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from com.cryptoapis.rest_apis.sdk.models.estimate_gas_limit403_response import EstimateGasLimit403Response

class TestEstimateGasLimit403Response(unittest.TestCase):
    """EstimateGasLimit403Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EstimateGasLimit403Response:
        """Test EstimateGasLimit403Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EstimateGasLimit403Response`
        """
        model = EstimateGasLimit403Response()
        if include_optional:
            return EstimateGasLimit403Response(
                api_version = '2023-04-25',
                request_id = '601c1710034ed6d407996b30',
                context = 'yourExampleString',
                error = com.cryptoapis.rest_apis.sdk.models.estimate_gas_limit_e403.EstimateGasLimitE403()
            )
        else:
            return EstimateGasLimit403Response(
                api_version = '2023-04-25',
                request_id = '601c1710034ed6d407996b30',
                error = com.cryptoapis.rest_apis.sdk.models.estimate_gas_limit_e403.EstimateGasLimitE403(),
        )
        """

    def testEstimateGasLimit403Response(self):
        """Test EstimateGasLimit403Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
