# coding: utf-8

"""
    CryptoAPIs

    Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.

    The version of the OpenAPI document: 2023-04-25
    Contact: developers@cryptoapis.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from com.cryptoapis.rest_apis.sdk.models.list_unconfirmed_transactions_by_address_ribse import ListUnconfirmedTransactionsByAddressRIBSE

class TestListUnconfirmedTransactionsByAddressRIBSE(unittest.TestCase):
    """ListUnconfirmedTransactionsByAddressRIBSE unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListUnconfirmedTransactionsByAddressRIBSE:
        """Test ListUnconfirmedTransactionsByAddressRIBSE
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListUnconfirmedTransactionsByAddressRIBSE`
        """
        model = ListUnconfirmedTransactionsByAddressRIBSE()
        if include_optional:
            return ListUnconfirmedTransactionsByAddressRIBSE(
                fee = com.cryptoapis.rest_apis.sdk.models.list_unconfirmed_transactions_by_address_ribse_fee.ListUnconfirmedTransactionsByAddressRIBSE_fee(
                    amount = '0.0122', 
                    unit = 'ETH', ),
                gas_limit = '552020',
                gas_price = com.cryptoapis.rest_apis.sdk.models.list_unconfirmed_transactions_by_address_ribse_gas_price.ListUnconfirmedTransactionsByAddressRIBSE_gasPrice(
                    amount = '2994782927', 
                    unit = 'ETH', ),
                input_data = '0x67a5cd0600000000000000000000000031f42841c2db5173425b5223809cf3a38fede360',
                nonce = 12,
                transaction_status = '0x1'
            )
        else:
            return ListUnconfirmedTransactionsByAddressRIBSE(
                fee = com.cryptoapis.rest_apis.sdk.models.list_unconfirmed_transactions_by_address_ribse_fee.ListUnconfirmedTransactionsByAddressRIBSE_fee(
                    amount = '0.0122', 
                    unit = 'ETH', ),
                gas_limit = '552020',
                gas_price = com.cryptoapis.rest_apis.sdk.models.list_unconfirmed_transactions_by_address_ribse_gas_price.ListUnconfirmedTransactionsByAddressRIBSE_gasPrice(
                    amount = '2994782927', 
                    unit = 'ETH', ),
                input_data = '0x67a5cd0600000000000000000000000031f42841c2db5173425b5223809cf3a38fede360',
                nonce = 12,
                transaction_status = '0x1',
        )
        """

    def testListUnconfirmedTransactionsByAddressRIBSE(self):
        """Test ListUnconfirmedTransactionsByAddressRIBSE"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
