# coding: utf-8

"""
    CryptoAPIs

    Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.

    The version of the OpenAPI document: 2023-04-25
    Contact: developers@cryptoapis.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from com.cryptoapis.rest_apis.sdk.models.list_unconfirmed_transactions_by_address_ribsd_vin_inner import ListUnconfirmedTransactionsByAddressRIBSDVinInner

class TestListUnconfirmedTransactionsByAddressRIBSDVinInner(unittest.TestCase):
    """ListUnconfirmedTransactionsByAddressRIBSDVinInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListUnconfirmedTransactionsByAddressRIBSDVinInner:
        """Test ListUnconfirmedTransactionsByAddressRIBSDVinInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListUnconfirmedTransactionsByAddressRIBSDVinInner`
        """
        model = ListUnconfirmedTransactionsByAddressRIBSDVinInner()
        if include_optional:
            return ListUnconfirmedTransactionsByAddressRIBSDVinInner(
                addresses = [
                    'DPzdWPsKaGvRn3AH7WjBpnNVHhAPELDY4o'
                    ],
                script_sig = com.cryptoapis.rest_apis.sdk.models.list_confirmed_transactions_by_address_ribsd_vin_inner_script_sig.ListConfirmedTransactionsByAddressRIBSD_vin_inner_scriptSig(
                    asm = '030483ff6271580681f4f7828c01df56d5aebfe982cbaa2922594be9eb6cf40206 OP_CHECKSIG', 
                    hex = '21030483ff6271580681f4f7828c01df56d5aebfe982cbaa2922594be9eb6cf40206ac', 
                    type = 'pubkey', ),
                sequence = 4294967295,
                txid = 'e1945b5d7e05f6d5ff77983d8a701b806722063559ed2528721b23fcb50baf06',
                txinwitness = [
                    'nY1qa6325pH5zfGjA3NW16xPYG8XYQjtbS'
                    ],
                value = '0.0225',
                vout = 1
            )
        else:
            return ListUnconfirmedTransactionsByAddressRIBSDVinInner(
                addresses = [
                    'DPzdWPsKaGvRn3AH7WjBpnNVHhAPELDY4o'
                    ],
                script_sig = com.cryptoapis.rest_apis.sdk.models.list_confirmed_transactions_by_address_ribsd_vin_inner_script_sig.ListConfirmedTransactionsByAddressRIBSD_vin_inner_scriptSig(
                    asm = '030483ff6271580681f4f7828c01df56d5aebfe982cbaa2922594be9eb6cf40206 OP_CHECKSIG', 
                    hex = '21030483ff6271580681f4f7828c01df56d5aebfe982cbaa2922594be9eb6cf40206ac', 
                    type = 'pubkey', ),
                sequence = 4294967295,
                txinwitness = [
                    'nY1qa6325pH5zfGjA3NW16xPYG8XYQjtbS'
                    ],
                value = '0.0225',
        )
        """

    def testListUnconfirmedTransactionsByAddressRIBSDVinInner(self):
        """Test ListUnconfirmedTransactionsByAddressRIBSDVinInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
