# coding: utf-8

"""
    CryptoAPIs

    Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.

    The version of the OpenAPI document: 2023-04-25
    Contact: developers@cryptoapis.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from com.cryptoapis.rest_apis.sdk.models.get_xrp_ripple_address_details_r_data import GetXRPRippleAddressDetailsRData

class TestGetXRPRippleAddressDetailsRData(unittest.TestCase):
    """GetXRPRippleAddressDetailsRData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetXRPRippleAddressDetailsRData:
        """Test GetXRPRippleAddressDetailsRData
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetXRPRippleAddressDetailsRData`
        """
        model = GetXRPRippleAddressDetailsRData()
        if include_optional:
            return GetXRPRippleAddressDetailsRData(
                item = com.cryptoapis.rest_apis.sdk.models.get_xrp_ripple_address_details_ri.GetXRPRippleAddressDetailsRI(
                    balance = com.cryptoapis.rest_apis.sdk.models.get_xrp_ripple_address_details_ri_balance.GetXRPRippleAddressDetailsRI_balance(
                        amount = '22.0000', 
                        unit = 'XRP', ), 
                    incoming_transactions_count = 1, 
                    outgoing_transactions_count = 1, 
                    sequence = 25648975, 
                    transactions_count = 2, )
            )
        else:
            return GetXRPRippleAddressDetailsRData(
                item = com.cryptoapis.rest_apis.sdk.models.get_xrp_ripple_address_details_ri.GetXRPRippleAddressDetailsRI(
                    balance = com.cryptoapis.rest_apis.sdk.models.get_xrp_ripple_address_details_ri_balance.GetXRPRippleAddressDetailsRI_balance(
                        amount = '22.0000', 
                        unit = 'XRP', ), 
                    incoming_transactions_count = 1, 
                    outgoing_transactions_count = 1, 
                    sequence = 25648975, 
                    transactions_count = 2, ),
        )
        """

    def testGetXRPRippleAddressDetailsRData(self):
        """Test GetXRPRippleAddressDetailsRData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
