# coding: utf-8

"""
    CryptoAPIs

    Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.

    The version of the OpenAPI document: 2023-04-25
    Contact: developers@cryptoapis.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from com.cryptoapis.rest_apis.sdk.models.list_logs_by_transaction_hash_ri import ListLogsByTransactionHashRI

class TestListLogsByTransactionHashRI(unittest.TestCase):
    """ListLogsByTransactionHashRI unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListLogsByTransactionHashRI:
        """Test ListLogsByTransactionHashRI
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListLogsByTransactionHashRI`
        """
        model = ListLogsByTransactionHashRI()
        if include_optional:
            return ListLogsByTransactionHashRI(
                address = '0xD04E772BC0d591fBD288f2E2a86aFA3D3CB647F8',
                data = '0x0000000000000000000000000000000000000000000018aa053302d4ad9e2c9c',
                is_removed = True,
                name = 'Transfer (index_topic_1 address from, index_topic_2 address to, uint256 value)',
                topics = [
                    '0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef'
                    ]
            )
        else:
            return ListLogsByTransactionHashRI(
                address = '0xD04E772BC0d591fBD288f2E2a86aFA3D3CB647F8',
                data = '0x0000000000000000000000000000000000000000000018aa053302d4ad9e2c9c',
                is_removed = True,
                topics = [
                    '0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef'
                    ],
        )
        """

    def testListLogsByTransactionHashRI(self):
        """Test ListLogsByTransactionHashRI"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
