# Hooks that can be registered by paco.extend
EXTEND_BASE_MODEL_HOOKS = []
CW_ALARM_ACTIONS_HOOK = None
CW_ALARM_HOOKS = []
CW_ALARM_DESCRIPTION_HOOK = None
CODESTAR_NOTIFICATION_RULE_HOOK = None
EVENTSRULE_NOTIFICATION_RULE_HOOK = None
CODEPIPELINE_CODEDEPLOY_ACTION_HOOK = None
CODEPIPELINE_CODEDEPLOY_CF_TEMPLATE_HOOK = None
CODEPIPELINE_CODEDEPLOY_INIT_STAGE_HOOK = None
CODEPIPELINE_CODEDEPLOY_UPDATE_DEPLOYMENT_GROUP_HOOK = None
SECURITY_GROUPS_HOOKS = []
S3_NOTIFICATIONS_HOOK = None
PRE_S3_BUCKET_POLICY_HOOK = None