from calc import add
from calc import sub
from calc import div
from calc import mul
from calc import pow
from calc import round_with_decimal_place
from calc import round_without_decimal_place
from calc import cbrt
from calc import cube
from calc import sqrt
from calc import square
from calc import advcalc