
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-04-09T13:32:54+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "f93afa81928ec647d2a4b2bcc482c6cbb2012b23",
 "version": "0.1.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
