"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file

Copyright 2020-2020 Exactpro (Exactpro Systems Limited)

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _Locator:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _LocatorEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_Locator.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    NOT_SET: _Locator.ValueType  # 0
    CSS_SELECTOR: _Locator.ValueType  # 1
    TAG_NAME: _Locator.ValueType  # 2
    ID: _Locator.ValueType  # 3
    XPATH: _Locator.ValueType  # 4

class Locator(_Locator, metaclass=_LocatorEnumTypeWrapper): ...

NOT_SET: Locator.ValueType  # 0
CSS_SELECTOR: Locator.ValueType  # 1
TAG_NAME: Locator.ValueType  # 2
ID: Locator.ValueType  # 3
XPATH: Locator.ValueType  # 4
global___Locator = Locator

@typing_extensions.final
class Open(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    URL_FIELD_NUMBER: builtins.int
    url: builtins.str
    def __init__(
        self,
        *,
        url: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["url", b"url"]) -> None: ...

global___Open = Open

@typing_extensions.final
class Click(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _Button:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _ButtonEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Click._Button.ValueType], builtins.type):  # noqa: F821
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        LEFT: Click._Button.ValueType  # 0
        RIGHT: Click._Button.ValueType  # 1
        MIDDLE: Click._Button.ValueType  # 2
        DOUBLE: Click._Button.ValueType  # 3

    class Button(_Button, metaclass=_ButtonEnumTypeWrapper): ...
    LEFT: Click.Button.ValueType  # 0
    RIGHT: Click.Button.ValueType  # 1
    MIDDLE: Click.Button.ValueType  # 2
    DOUBLE: Click.Button.ValueType  # 3

    @typing_extensions.final
    class ModifiersList(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        class _Modifier:
            ValueType = typing.NewType("ValueType", builtins.int)
            V: typing_extensions.TypeAlias = ValueType

        class _ModifierEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Click.ModifiersList._Modifier.ValueType], builtins.type):  # noqa: F821
            DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
            CTRL: Click.ModifiersList._Modifier.ValueType  # 0
            SHIFT: Click.ModifiersList._Modifier.ValueType  # 1
            ALT: Click.ModifiersList._Modifier.ValueType  # 2

        class Modifier(_Modifier, metaclass=_ModifierEnumTypeWrapper): ...
        CTRL: Click.ModifiersList.Modifier.ValueType  # 0
        SHIFT: Click.ModifiersList.Modifier.ValueType  # 1
        ALT: Click.ModifiersList.Modifier.ValueType  # 2

        MODIFIER_FIELD_NUMBER: builtins.int
        @property
        def modifier(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[global___Click.ModifiersList.Modifier.ValueType]: ...
        def __init__(
            self,
            *,
            modifier: collections.abc.Iterable[global___Click.ModifiersList.Modifier.ValueType] | None = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["modifier", b"modifier"]) -> None: ...

    WAIT_FIELD_NUMBER: builtins.int
    LOCATOR_FIELD_NUMBER: builtins.int
    MATCHER_FIELD_NUMBER: builtins.int
    WEBID_FIELD_NUMBER: builtins.int
    BUTTON_FIELD_NUMBER: builtins.int
    XOFFSET_FIELD_NUMBER: builtins.int
    YOFFSET_FIELD_NUMBER: builtins.int
    MODIFIERS_FIELD_NUMBER: builtins.int
    wait: builtins.int
    locator: global___Locator.ValueType
    matcher: builtins.str
    webId: builtins.str
    button: global___Click.Button.ValueType
    xOffset: builtins.int
    yOffset: builtins.int
    @property
    def modifiers(self) -> global___Click.ModifiersList: ...
    def __init__(
        self,
        *,
        wait: builtins.int = ...,
        locator: global___Locator.ValueType = ...,
        matcher: builtins.str = ...,
        webId: builtins.str = ...,
        button: global___Click.Button.ValueType = ...,
        xOffset: builtins.int = ...,
        yOffset: builtins.int = ...,
        modifiers: global___Click.ModifiersList | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["modifiers", b"modifiers"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["button", b"button", "locator", b"locator", "matcher", b"matcher", "modifiers", b"modifiers", "wait", b"wait", "webId", b"webId", "xOffset", b"xOffset", "yOffset", b"yOffset"]) -> None: ...

global___Click = Click

@typing_extensions.final
class SetCheckbox(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WAIT_FIELD_NUMBER: builtins.int
    LOCATOR_FIELD_NUMBER: builtins.int
    MATCHER_FIELD_NUMBER: builtins.int
    WEBID_FIELD_NUMBER: builtins.int
    CHECKED_FIELD_NUMBER: builtins.int
    wait: builtins.int
    locator: global___Locator.ValueType
    matcher: builtins.str
    webId: builtins.str
    checked: builtins.bool
    def __init__(
        self,
        *,
        wait: builtins.int = ...,
        locator: global___Locator.ValueType = ...,
        matcher: builtins.str = ...,
        webId: builtins.str = ...,
        checked: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["checked", b"checked", "locator", b"locator", "matcher", b"matcher", "wait", b"wait", "webId", b"webId"]) -> None: ...

global___SetCheckbox = SetCheckbox

@typing_extensions.final
class SendKeys(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WAIT_FIELD_NUMBER: builtins.int
    LOCATOR_FIELD_NUMBER: builtins.int
    MATCHER_FIELD_NUMBER: builtins.int
    WEBID_FIELD_NUMBER: builtins.int
    TEXT_FIELD_NUMBER: builtins.int
    WAIT2_FIELD_NUMBER: builtins.int
    LOCATOR2_FIELD_NUMBER: builtins.int
    MATCHER2_FIELD_NUMBER: builtins.int
    TEXT2_FIELD_NUMBER: builtins.int
    CANBEDISABLED_FIELD_NUMBER: builtins.int
    CLEAR_FIELD_NUMBER: builtins.int
    CHECKINPUT_FIELD_NUMBER: builtins.int
    NEEDCLICK_FIELD_NUMBER: builtins.int
    wait: builtins.int
    locator: global___Locator.ValueType
    matcher: builtins.str
    webId: builtins.str
    text: builtins.str
    wait2: builtins.int
    locator2: global___Locator.ValueType
    matcher2: builtins.str
    text2: builtins.str
    canBeDisabled: builtins.bool
    clear: builtins.bool
    checkInput: builtins.bool
    needClick: builtins.bool
    def __init__(
        self,
        *,
        wait: builtins.int = ...,
        locator: global___Locator.ValueType = ...,
        matcher: builtins.str = ...,
        webId: builtins.str = ...,
        text: builtins.str = ...,
        wait2: builtins.int = ...,
        locator2: global___Locator.ValueType = ...,
        matcher2: builtins.str = ...,
        text2: builtins.str = ...,
        canBeDisabled: builtins.bool = ...,
        clear: builtins.bool = ...,
        checkInput: builtins.bool = ...,
        needClick: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["canBeDisabled", b"canBeDisabled", "checkInput", b"checkInput", "clear", b"clear", "locator", b"locator", "locator2", b"locator2", "matcher", b"matcher", "matcher2", b"matcher2", "needClick", b"needClick", "text", b"text", "text2", b"text2", "wait", b"wait", "wait2", b"wait2", "webId", b"webId"]) -> None: ...

global___SendKeys = SendKeys

@typing_extensions.final
class WaitForElement(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SECONDS_FIELD_NUMBER: builtins.int
    LOCATOR_FIELD_NUMBER: builtins.int
    MATCHER_FIELD_NUMBER: builtins.int
    WEBID_FIELD_NUMBER: builtins.int
    seconds: builtins.int
    locator: global___Locator.ValueType
    matcher: builtins.str
    webId: builtins.str
    def __init__(
        self,
        *,
        seconds: builtins.int = ...,
        locator: global___Locator.ValueType = ...,
        matcher: builtins.str = ...,
        webId: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["locator", b"locator", "matcher", b"matcher", "seconds", b"seconds", "webId", b"webId"]) -> None: ...

global___WaitForElement = WaitForElement

@typing_extensions.final
class WaitForNew(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SECONDS_FIELD_NUMBER: builtins.int
    CHECKMILLIS_FIELD_NUMBER: builtins.int
    LOCATOR_FIELD_NUMBER: builtins.int
    MATCHER_FIELD_NUMBER: builtins.int
    WEBID_FIELD_NUMBER: builtins.int
    seconds: builtins.int
    checkMillis: builtins.int
    locator: global___Locator.ValueType
    matcher: builtins.str
    webId: builtins.str
    def __init__(
        self,
        *,
        seconds: builtins.int = ...,
        checkMillis: builtins.int = ...,
        locator: global___Locator.ValueType = ...,
        matcher: builtins.str = ...,
        webId: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["checkMillis", b"checkMillis", "locator", b"locator", "matcher", b"matcher", "seconds", b"seconds", "webId", b"webId"]) -> None: ...

global___WaitForNew = WaitForNew

@typing_extensions.final
class Wait(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SECONDS_FIELD_NUMBER: builtins.int
    seconds: builtins.int
    def __init__(
        self,
        *,
        seconds: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["seconds", b"seconds"]) -> None: ...

global___Wait = Wait

@typing_extensions.final
class GetElement(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WAIT_FIELD_NUMBER: builtins.int
    LOCATOR_FIELD_NUMBER: builtins.int
    MATCHER_FIELD_NUMBER: builtins.int
    WEBID_FIELD_NUMBER: builtins.int
    ID_FIELD_NUMBER: builtins.int
    wait: builtins.int
    locator: global___Locator.ValueType
    matcher: builtins.str
    webId: builtins.str
    id: builtins.str
    def __init__(
        self,
        *,
        wait: builtins.int = ...,
        locator: global___Locator.ValueType = ...,
        matcher: builtins.str = ...,
        webId: builtins.str = ...,
        id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["id", b"id", "locator", b"locator", "matcher", b"matcher", "wait", b"wait", "webId", b"webId"]) -> None: ...

global___GetElement = GetElement

@typing_extensions.final
class GetElementInnerHtml(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WAIT_FIELD_NUMBER: builtins.int
    LOCATOR_FIELD_NUMBER: builtins.int
    MATCHER_FIELD_NUMBER: builtins.int
    WEBID_FIELD_NUMBER: builtins.int
    ID_FIELD_NUMBER: builtins.int
    wait: builtins.int
    locator: global___Locator.ValueType
    matcher: builtins.str
    webId: builtins.str
    id: builtins.str
    def __init__(
        self,
        *,
        wait: builtins.int = ...,
        locator: global___Locator.ValueType = ...,
        matcher: builtins.str = ...,
        webId: builtins.str = ...,
        id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["id", b"id", "locator", b"locator", "matcher", b"matcher", "wait", b"wait", "webId", b"webId"]) -> None: ...

global___GetElementInnerHtml = GetElementInnerHtml

@typing_extensions.final
class GetElementValue(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WAIT_FIELD_NUMBER: builtins.int
    LOCATOR_FIELD_NUMBER: builtins.int
    MATCHER_FIELD_NUMBER: builtins.int
    WEBID_FIELD_NUMBER: builtins.int
    wait: builtins.int
    locator: global___Locator.ValueType
    matcher: builtins.str
    webId: builtins.str
    def __init__(
        self,
        *,
        wait: builtins.int = ...,
        locator: global___Locator.ValueType = ...,
        matcher: builtins.str = ...,
        webId: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["locator", b"locator", "matcher", b"matcher", "wait", b"wait", "webId", b"webId"]) -> None: ...

global___GetElementValue = GetElementValue

@typing_extensions.final
class GetElementAttribute(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WAIT_FIELD_NUMBER: builtins.int
    LOCATOR_FIELD_NUMBER: builtins.int
    MATCHER_FIELD_NUMBER: builtins.int
    WEBID_FIELD_NUMBER: builtins.int
    ATTRIBUTE_FIELD_NUMBER: builtins.int
    wait: builtins.int
    locator: global___Locator.ValueType
    matcher: builtins.str
    webId: builtins.str
    attribute: builtins.str
    def __init__(
        self,
        *,
        wait: builtins.int = ...,
        locator: global___Locator.ValueType = ...,
        matcher: builtins.str = ...,
        webId: builtins.str = ...,
        attribute: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["attribute", b"attribute", "locator", b"locator", "matcher", b"matcher", "wait", b"wait", "webId", b"webId"]) -> None: ...

global___GetElementAttribute = GetElementAttribute

@typing_extensions.final
class GetDynamicTable(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WAIT_FIELD_NUMBER: builtins.int
    LOCATOR_FIELD_NUMBER: builtins.int
    MATCHER_FIELD_NUMBER: builtins.int
    WEBID_FIELD_NUMBER: builtins.int
    wait: builtins.int
    locator: global___Locator.ValueType
    matcher: builtins.str
    webId: builtins.str
    def __init__(
        self,
        *,
        wait: builtins.int = ...,
        locator: global___Locator.ValueType = ...,
        matcher: builtins.str = ...,
        webId: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["locator", b"locator", "matcher", b"matcher", "wait", b"wait", "webId", b"webId"]) -> None: ...

global___GetDynamicTable = GetDynamicTable

@typing_extensions.final
class ScrollTo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WAIT_FIELD_NUMBER: builtins.int
    LOCATOR_FIELD_NUMBER: builtins.int
    MATCHER_FIELD_NUMBER: builtins.int
    WEBID_FIELD_NUMBER: builtins.int
    wait: builtins.int
    locator: global___Locator.ValueType
    matcher: builtins.str
    webId: builtins.str
    def __init__(
        self,
        *,
        wait: builtins.int = ...,
        locator: global___Locator.ValueType = ...,
        matcher: builtins.str = ...,
        webId: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["locator", b"locator", "matcher", b"matcher", "wait", b"wait", "webId", b"webId"]) -> None: ...

global___ScrollTo = ScrollTo

@typing_extensions.final
class ScrollDivTo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WAIT_FIELD_NUMBER: builtins.int
    LOCATOR_FIELD_NUMBER: builtins.int
    MATCHER_FIELD_NUMBER: builtins.int
    WEBID_FIELD_NUMBER: builtins.int
    WAIT2_FIELD_NUMBER: builtins.int
    LOCATOR2_FIELD_NUMBER: builtins.int
    MATCHER2_FIELD_NUMBER: builtins.int
    YOFFSET_FIELD_NUMBER: builtins.int
    wait: builtins.int
    locator: global___Locator.ValueType
    matcher: builtins.str
    webId: builtins.str
    wait2: builtins.int
    locator2: global___Locator.ValueType
    matcher2: builtins.str
    yOffset: builtins.int
    def __init__(
        self,
        *,
        wait: builtins.int = ...,
        locator: global___Locator.ValueType = ...,
        matcher: builtins.str = ...,
        webId: builtins.str = ...,
        wait2: builtins.int = ...,
        locator2: global___Locator.ValueType = ...,
        matcher2: builtins.str = ...,
        yOffset: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["locator", b"locator", "locator2", b"locator2", "matcher", b"matcher", "matcher2", b"matcher2", "wait", b"wait", "wait2", b"wait2", "webId", b"webId", "yOffset", b"yOffset"]) -> None: ...

global___ScrollDivTo = ScrollDivTo

@typing_extensions.final
class ScrollDivUntil(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _Direction:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _DirectionEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[ScrollDivUntil._Direction.ValueType], builtins.type):  # noqa: F821
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        BOTH: ScrollDivUntil._Direction.ValueType  # 0
        UP: ScrollDivUntil._Direction.ValueType  # 1
        DOWN: ScrollDivUntil._Direction.ValueType  # 2

    class Direction(_Direction, metaclass=_DirectionEnumTypeWrapper): ...
    BOTH: ScrollDivUntil.Direction.ValueType  # 0
    UP: ScrollDivUntil.Direction.ValueType  # 1
    DOWN: ScrollDivUntil.Direction.ValueType  # 2

    WAIT_FIELD_NUMBER: builtins.int
    LOCATOR_FIELD_NUMBER: builtins.int
    MATCHER_FIELD_NUMBER: builtins.int
    WEBID_FIELD_NUMBER: builtins.int
    WAIT2_FIELD_NUMBER: builtins.int
    LOCATOR2_FIELD_NUMBER: builtins.int
    MATCHER2_FIELD_NUMBER: builtins.int
    SEARCHDIR_FIELD_NUMBER: builtins.int
    SEARCHOFFSET_FIELD_NUMBER: builtins.int
    DOSCROLLTO_FIELD_NUMBER: builtins.int
    YOFFSET_FIELD_NUMBER: builtins.int
    wait: builtins.int
    locator: global___Locator.ValueType
    matcher: builtins.str
    webId: builtins.str
    wait2: builtins.int
    locator2: global___Locator.ValueType
    matcher2: builtins.str
    searchDir: global___ScrollDivUntil.Direction.ValueType
    searchOffset: builtins.int
    doScrollTo: builtins.bool
    yOffset: builtins.int
    def __init__(
        self,
        *,
        wait: builtins.int = ...,
        locator: global___Locator.ValueType = ...,
        matcher: builtins.str = ...,
        webId: builtins.str = ...,
        wait2: builtins.int = ...,
        locator2: global___Locator.ValueType = ...,
        matcher2: builtins.str = ...,
        searchDir: global___ScrollDivUntil.Direction.ValueType = ...,
        searchOffset: builtins.int = ...,
        doScrollTo: builtins.bool = ...,
        yOffset: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["doScrollTo", b"doScrollTo", "locator", b"locator", "locator2", b"locator2", "matcher", b"matcher", "matcher2", b"matcher2", "searchDir", b"searchDir", "searchOffset", b"searchOffset", "wait", b"wait", "wait2", b"wait2", "webId", b"webId", "yOffset", b"yOffset"]) -> None: ...

global___ScrollDivUntil = ScrollDivUntil

@typing_extensions.final
class PageSource(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___PageSource = PageSource

@typing_extensions.final
class Refresh(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___Refresh = Refresh

@typing_extensions.final
class Select(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WAIT_FIELD_NUMBER: builtins.int
    LOCATOR_FIELD_NUMBER: builtins.int
    MATCHER_FIELD_NUMBER: builtins.int
    WEBID_FIELD_NUMBER: builtins.int
    TEXT_FIELD_NUMBER: builtins.int
    DEFAULT_FIELD_NUMBER: builtins.int
    NOOPTIONALFAIL_FIELD_NUMBER: builtins.int
    wait: builtins.int
    locator: global___Locator.ValueType
    matcher: builtins.str
    webId: builtins.str
    text: builtins.str
    default: builtins.str
    noOptionalFail: builtins.bool
    def __init__(
        self,
        *,
        wait: builtins.int = ...,
        locator: global___Locator.ValueType = ...,
        matcher: builtins.str = ...,
        webId: builtins.str = ...,
        text: builtins.str = ...,
        default: builtins.str = ...,
        noOptionalFail: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["default", b"default", "locator", b"locator", "matcher", b"matcher", "noOptionalFail", b"noOptionalFail", "text", b"text", "wait", b"wait", "webId", b"webId"]) -> None: ...

global___Select = Select

@typing_extensions.final
class ClearElement(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WAIT_FIELD_NUMBER: builtins.int
    LOCATOR_FIELD_NUMBER: builtins.int
    MATCHER_FIELD_NUMBER: builtins.int
    WEBID_FIELD_NUMBER: builtins.int
    wait: builtins.int
    locator: global___Locator.ValueType
    matcher: builtins.str
    webId: builtins.str
    def __init__(
        self,
        *,
        wait: builtins.int = ...,
        locator: global___Locator.ValueType = ...,
        matcher: builtins.str = ...,
        webId: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["locator", b"locator", "matcher", b"matcher", "wait", b"wait", "webId", b"webId"]) -> None: ...

global___ClearElement = ClearElement

@typing_extensions.final
class Output(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TEXT_FIELD_NUMBER: builtins.int
    text: builtins.str
    def __init__(
        self,
        *,
        text: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["text", b"text"]) -> None: ...

global___Output = Output

@typing_extensions.final
class FindElement(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WAIT_FIELD_NUMBER: builtins.int
    LOCATOR_FIELD_NUMBER: builtins.int
    MATCHER_FIELD_NUMBER: builtins.int
    WEBID_FIELD_NUMBER: builtins.int
    ID_FIELD_NUMBER: builtins.int
    wait: builtins.int
    locator: global___Locator.ValueType
    matcher: builtins.str
    webId: builtins.str
    id: builtins.str
    def __init__(
        self,
        *,
        wait: builtins.int = ...,
        locator: global___Locator.ValueType = ...,
        matcher: builtins.str = ...,
        webId: builtins.str = ...,
        id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["id", b"id", "locator", b"locator", "matcher", b"matcher", "wait", b"wait", "webId", b"webId"]) -> None: ...

global___FindElement = FindElement

@typing_extensions.final
class KeyAction(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _ActionType:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _ActionTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[KeyAction._ActionType.ValueType], builtins.type):  # noqa: F821
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        PRESS: KeyAction._ActionType.ValueType  # 0
        UP: KeyAction._ActionType.ValueType  # 1
        DOWN: KeyAction._ActionType.ValueType  # 2

    class ActionType(_ActionType, metaclass=_ActionTypeEnumTypeWrapper): ...
    PRESS: KeyAction.ActionType.ValueType  # 0
    UP: KeyAction.ActionType.ValueType  # 1
    DOWN: KeyAction.ActionType.ValueType  # 2

    KEY_FIELD_NUMBER: builtins.int
    KEYACTION_FIELD_NUMBER: builtins.int
    key: builtins.str
    keyAction: global___KeyAction.ActionType.ValueType
    def __init__(
        self,
        *,
        key: builtins.str = ...,
        keyAction: global___KeyAction.ActionType.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["key", b"key", "keyAction", b"keyAction"]) -> None: ...

global___KeyAction = KeyAction

@typing_extensions.final
class PressKey(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    KEY_FIELD_NUMBER: builtins.int
    key: builtins.str
    def __init__(
        self,
        *,
        key: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["key", b"key"]) -> None: ...

global___PressKey = PressKey

@typing_extensions.final
class SendKeysToActive(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TEXT_FIELD_NUMBER: builtins.int
    TEXT2_FIELD_NUMBER: builtins.int
    text: builtins.str
    text2: builtins.str
    def __init__(
        self,
        *,
        text: builtins.str = ...,
        text2: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["text", b"text", "text2", b"text2"]) -> None: ...

global___SendKeysToActive = SendKeysToActive

@typing_extensions.final
class UploadFile(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WAIT_FIELD_NUMBER: builtins.int
    LOCATOR_FIELD_NUMBER: builtins.int
    MATCHER_FIELD_NUMBER: builtins.int
    WEBID_FIELD_NUMBER: builtins.int
    ABSOLUTEPATH_FIELD_NUMBER: builtins.int
    wait: builtins.int
    locator: global___Locator.ValueType
    matcher: builtins.str
    webId: builtins.str
    absolutePath: builtins.str
    def __init__(
        self,
        *,
        wait: builtins.int = ...,
        locator: global___Locator.ValueType = ...,
        matcher: builtins.str = ...,
        webId: builtins.str = ...,
        absolutePath: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["absolutePath", b"absolutePath", "locator", b"locator", "matcher", b"matcher", "wait", b"wait", "webId", b"webId"]) -> None: ...

global___UploadFile = UploadFile

@typing_extensions.final
class DownloadFile(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _DownloadActionType:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _DownloadActionTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[DownloadFile._DownloadActionType.ValueType], builtins.type):  # noqa: F821
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        SNAPSHOT: DownloadFile._DownloadActionType.ValueType  # 0
        DOWNLOAD: DownloadFile._DownloadActionType.ValueType  # 1

    class DownloadActionType(_DownloadActionType, metaclass=_DownloadActionTypeEnumTypeWrapper): ...
    SNAPSHOT: DownloadFile.DownloadActionType.ValueType  # 0
    DOWNLOAD: DownloadFile.DownloadActionType.ValueType  # 1

    WAIT_FIELD_NUMBER: builtins.int
    ACTIONTYPE_FIELD_NUMBER: builtins.int
    LOCALPATH_FIELD_NUMBER: builtins.int
    wait: builtins.int
    actionType: global___DownloadFile.DownloadActionType.ValueType
    localPath: builtins.bool
    def __init__(
        self,
        *,
        wait: builtins.int = ...,
        actionType: global___DownloadFile.DownloadActionType.ValueType = ...,
        localPath: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["actionType", b"actionType", "localPath", b"localPath", "wait", b"wait"]) -> None: ...

global___DownloadFile = DownloadFile

@typing_extensions.final
class SwitchWindow(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WINDOW_FIELD_NUMBER: builtins.int
    window: builtins.int
    def __init__(
        self,
        *,
        window: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["window", b"window"]) -> None: ...

global___SwitchWindow = SwitchWindow

@typing_extensions.final
class CloseWindow(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___CloseWindow = CloseWindow

@typing_extensions.final
class GetCurrentURL(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___GetCurrentURL = GetCurrentURL

@typing_extensions.final
class SetZoom(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VALUE_FIELD_NUMBER: builtins.int
    value: builtins.str
    def __init__(
        self,
        *,
        value: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["value", b"value"]) -> None: ...

global___SetZoom = SetZoom

@typing_extensions.final
class DurationStart(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    id: builtins.str
    def __init__(
        self,
        *,
        id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["id", b"id"]) -> None: ...

global___DurationStart = DurationStart

@typing_extensions.final
class GetDuration(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STARTID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    startId: builtins.str
    name: builtins.str
    def __init__(
        self,
        *,
        startId: builtins.str = ...,
        name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["name", b"name", "startId", b"startId"]) -> None: ...

global___GetDuration = GetDuration

@typing_extensions.final
class StoreElementState(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WAIT_FIELD_NUMBER: builtins.int
    LOCATOR_FIELD_NUMBER: builtins.int
    MATCHER_FIELD_NUMBER: builtins.int
    WEBID_FIELD_NUMBER: builtins.int
    ID_FIELD_NUMBER: builtins.int
    wait: builtins.int
    locator: global___Locator.ValueType
    matcher: builtins.str
    webId: builtins.str
    id: builtins.str
    def __init__(
        self,
        *,
        wait: builtins.int = ...,
        locator: global___Locator.ValueType = ...,
        matcher: builtins.str = ...,
        webId: builtins.str = ...,
        id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["id", b"id", "locator", b"locator", "matcher", b"matcher", "wait", b"wait", "webId", b"webId"]) -> None: ...

global___StoreElementState = StoreElementState

@typing_extensions.final
class WaitForChanges(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SECONDS_FIELD_NUMBER: builtins.int
    CHECKMILLIS_FIELD_NUMBER: builtins.int
    LOCATOR_FIELD_NUMBER: builtins.int
    MATCHER_FIELD_NUMBER: builtins.int
    WEBID_FIELD_NUMBER: builtins.int
    SCREENSHOTID_FIELD_NUMBER: builtins.int
    seconds: builtins.int
    checkMillis: builtins.int
    locator: global___Locator.ValueType
    matcher: builtins.str
    webId: builtins.str
    screenshotId: builtins.str
    def __init__(
        self,
        *,
        seconds: builtins.int = ...,
        checkMillis: builtins.int = ...,
        locator: global___Locator.ValueType = ...,
        matcher: builtins.str = ...,
        webId: builtins.str = ...,
        screenshotId: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["checkMillis", b"checkMillis", "locator", b"locator", "matcher", b"matcher", "screenshotId", b"screenshotId", "seconds", b"seconds", "webId", b"webId"]) -> None: ...

global___WaitForChanges = WaitForChanges

@typing_extensions.final
class AcceptAlert(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WAIT_FIELD_NUMBER: builtins.int
    wait: builtins.int
    def __init__(
        self,
        *,
        wait: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["wait", b"wait"]) -> None: ...

global___AcceptAlert = AcceptAlert

@typing_extensions.final
class DismissAlert(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WAIT_FIELD_NUMBER: builtins.int
    wait: builtins.int
    def __init__(
        self,
        *,
        wait: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["wait", b"wait"]) -> None: ...

global___DismissAlert = DismissAlert

@typing_extensions.final
class CheckImageAvailability(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WAIT_FIELD_NUMBER: builtins.int
    LOCATOR_FIELD_NUMBER: builtins.int
    MATCHER_FIELD_NUMBER: builtins.int
    WEBID_FIELD_NUMBER: builtins.int
    wait: builtins.int
    locator: global___Locator.ValueType
    matcher: builtins.str
    webId: builtins.str
    def __init__(
        self,
        *,
        wait: builtins.int = ...,
        locator: global___Locator.ValueType = ...,
        matcher: builtins.str = ...,
        webId: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["locator", b"locator", "matcher", b"matcher", "wait", b"wait", "webId", b"webId"]) -> None: ...

global___CheckImageAvailability = CheckImageAvailability

@typing_extensions.final
class GetScreenshot(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    name: builtins.str
    def __init__(
        self,
        *,
        name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["name", b"name"]) -> None: ...

global___GetScreenshot = GetScreenshot

@typing_extensions.final
class GetElementScreenshot(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WAIT_FIELD_NUMBER: builtins.int
    LOCATOR_FIELD_NUMBER: builtins.int
    MATCHER_FIELD_NUMBER: builtins.int
    WEBID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    wait: builtins.int
    locator: global___Locator.ValueType
    matcher: builtins.str
    webId: builtins.str
    name: builtins.str
    def __init__(
        self,
        *,
        wait: builtins.int = ...,
        locator: global___Locator.ValueType = ...,
        matcher: builtins.str = ...,
        webId: builtins.str = ...,
        name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["locator", b"locator", "matcher", b"matcher", "name", b"name", "wait", b"wait", "webId", b"webId"]) -> None: ...

global___GetElementScreenshot = GetElementScreenshot

@typing_extensions.final
class ExecuteJS(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    COMMANDS_FIELD_NUMBER: builtins.int
    commands: builtins.str
    def __init__(
        self,
        *,
        commands: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["commands", b"commands"]) -> None: ...

global___ExecuteJS = ExecuteJS

@typing_extensions.final
class ExecuteJSElement(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WAIT_FIELD_NUMBER: builtins.int
    LOCATOR_FIELD_NUMBER: builtins.int
    MATCHER_FIELD_NUMBER: builtins.int
    WEBID_FIELD_NUMBER: builtins.int
    COMMANDS_FIELD_NUMBER: builtins.int
    wait: builtins.int
    locator: global___Locator.ValueType
    matcher: builtins.str
    webId: builtins.str
    commands: builtins.str
    def __init__(
        self,
        *,
        wait: builtins.int = ...,
        locator: global___Locator.ValueType = ...,
        matcher: builtins.str = ...,
        webId: builtins.str = ...,
        commands: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["commands", b"commands", "locator", b"locator", "matcher", b"matcher", "wait", b"wait", "webId", b"webId"]) -> None: ...

global___ExecuteJSElement = ExecuteJSElement

@typing_extensions.final
class SelectFrame(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WAIT_FIELD_NUMBER: builtins.int
    LOCATOR_FIELD_NUMBER: builtins.int
    MATCHER_FIELD_NUMBER: builtins.int
    wait: builtins.int
    locator: global___Locator.ValueType
    matcher: builtins.str
    def __init__(
        self,
        *,
        wait: builtins.int = ...,
        locator: global___Locator.ValueType = ...,
        matcher: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["locator", b"locator", "matcher", b"matcher", "wait", b"wait"]) -> None: ...

global___SelectFrame = SelectFrame

@typing_extensions.final
class RhWebActionList(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WEBACTIONLIST_FIELD_NUMBER: builtins.int
    @property
    def webActionList(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___RhWebActions]: ...
    def __init__(
        self,
        *,
        webActionList: collections.abc.Iterable[global___RhWebActions] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["webActionList", b"webActionList"]) -> None: ...

global___RhWebActionList = RhWebActionList

@typing_extensions.final
class RhWebActions(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OPEN_FIELD_NUMBER: builtins.int
    CLICK_FIELD_NUMBER: builtins.int
    SETCHECKBOX_FIELD_NUMBER: builtins.int
    SENDKEYS_FIELD_NUMBER: builtins.int
    WAITFORELEMENT_FIELD_NUMBER: builtins.int
    WAITFORNEW_FIELD_NUMBER: builtins.int
    WAIT_FIELD_NUMBER: builtins.int
    GETELEMENT_FIELD_NUMBER: builtins.int
    GETELEMENTINNERHTML_FIELD_NUMBER: builtins.int
    GETELEMENTVALUE_FIELD_NUMBER: builtins.int
    GETELEMENTATTRIBUTE_FIELD_NUMBER: builtins.int
    GETDYNAMICTABLE_FIELD_NUMBER: builtins.int
    SCROLLTO_FIELD_NUMBER: builtins.int
    SCROLLDIVTO_FIELD_NUMBER: builtins.int
    SCROLLDIVUNTIL_FIELD_NUMBER: builtins.int
    PAGESOURCE_FIELD_NUMBER: builtins.int
    REFRESH_FIELD_NUMBER: builtins.int
    SELECT_FIELD_NUMBER: builtins.int
    CLEARELEMENT_FIELD_NUMBER: builtins.int
    OUTPUT_FIELD_NUMBER: builtins.int
    FINDELEMENT_FIELD_NUMBER: builtins.int
    KEYACTION_FIELD_NUMBER: builtins.int
    PRESSKEY_FIELD_NUMBER: builtins.int
    SENDKEYSTOACTIVE_FIELD_NUMBER: builtins.int
    UPLOADFILE_FIELD_NUMBER: builtins.int
    DOWNLOADFILE_FIELD_NUMBER: builtins.int
    SWITCHWINDOW_FIELD_NUMBER: builtins.int
    CLOSEWINDOW_FIELD_NUMBER: builtins.int
    GETCURRENTURL_FIELD_NUMBER: builtins.int
    SETZOOM_FIELD_NUMBER: builtins.int
    DURATIONSTART_FIELD_NUMBER: builtins.int
    GETDURATION_FIELD_NUMBER: builtins.int
    GETELEMENTSCREENSHOT_FIELD_NUMBER: builtins.int
    WAITFORCHANGES_FIELD_NUMBER: builtins.int
    ACCEPTALERT_FIELD_NUMBER: builtins.int
    DISMISSALERT_FIELD_NUMBER: builtins.int
    CHECKIMAGEAVAILABILITY_FIELD_NUMBER: builtins.int
    GETSCREENSHOT_FIELD_NUMBER: builtins.int
    STOREELEMENTSTATE_FIELD_NUMBER: builtins.int
    EXECUTEJS_FIELD_NUMBER: builtins.int
    EXECUTEJSELEMENT_FIELD_NUMBER: builtins.int
    SELECTFRAME_FIELD_NUMBER: builtins.int
    @property
    def open(self) -> global___Open: ...
    @property
    def click(self) -> global___Click: ...
    @property
    def setCheckbox(self) -> global___SetCheckbox: ...
    @property
    def sendKeys(self) -> global___SendKeys: ...
    @property
    def waitForElement(self) -> global___WaitForElement: ...
    @property
    def waitForNew(self) -> global___WaitForNew: ...
    @property
    def wait(self) -> global___Wait: ...
    @property
    def getElement(self) -> global___GetElement: ...
    @property
    def getElementInnerHtml(self) -> global___GetElementInnerHtml: ...
    @property
    def getElementValue(self) -> global___GetElementValue: ...
    @property
    def getElementAttribute(self) -> global___GetElementAttribute: ...
    @property
    def getDynamicTable(self) -> global___GetDynamicTable: ...
    @property
    def scrollTo(self) -> global___ScrollTo: ...
    @property
    def scrollDivTo(self) -> global___ScrollDivTo: ...
    @property
    def scrollDivUntil(self) -> global___ScrollDivUntil: ...
    @property
    def pageSource(self) -> global___PageSource: ...
    @property
    def refresh(self) -> global___Refresh: ...
    @property
    def select(self) -> global___Select: ...
    @property
    def clearElement(self) -> global___ClearElement: ...
    @property
    def output(self) -> global___Output: ...
    @property
    def findElement(self) -> global___FindElement: ...
    @property
    def keyAction(self) -> global___KeyAction: ...
    @property
    def pressKey(self) -> global___PressKey: ...
    @property
    def sendKeysToActive(self) -> global___SendKeysToActive: ...
    @property
    def uploadFile(self) -> global___UploadFile: ...
    @property
    def downloadFile(self) -> global___DownloadFile: ...
    @property
    def switchWindow(self) -> global___SwitchWindow: ...
    @property
    def closeWindow(self) -> global___CloseWindow: ...
    @property
    def getCurrentURL(self) -> global___GetCurrentURL: ...
    @property
    def setZoom(self) -> global___SetZoom: ...
    @property
    def durationStart(self) -> global___DurationStart: ...
    @property
    def getDuration(self) -> global___GetDuration: ...
    @property
    def getElementScreenshot(self) -> global___GetElementScreenshot: ...
    @property
    def waitForChanges(self) -> global___WaitForChanges: ...
    @property
    def acceptAlert(self) -> global___AcceptAlert: ...
    @property
    def dismissAlert(self) -> global___DismissAlert: ...
    @property
    def checkImageAvailability(self) -> global___CheckImageAvailability: ...
    @property
    def getScreenshot(self) -> global___GetScreenshot: ...
    @property
    def storeElementState(self) -> global___StoreElementState: ...
    @property
    def executeJs(self) -> global___ExecuteJS: ...
    @property
    def executeJsElement(self) -> global___ExecuteJSElement: ...
    @property
    def selectFrame(self) -> global___SelectFrame: ...
    def __init__(
        self,
        *,
        open: global___Open | None = ...,
        click: global___Click | None = ...,
        setCheckbox: global___SetCheckbox | None = ...,
        sendKeys: global___SendKeys | None = ...,
        waitForElement: global___WaitForElement | None = ...,
        waitForNew: global___WaitForNew | None = ...,
        wait: global___Wait | None = ...,
        getElement: global___GetElement | None = ...,
        getElementInnerHtml: global___GetElementInnerHtml | None = ...,
        getElementValue: global___GetElementValue | None = ...,
        getElementAttribute: global___GetElementAttribute | None = ...,
        getDynamicTable: global___GetDynamicTable | None = ...,
        scrollTo: global___ScrollTo | None = ...,
        scrollDivTo: global___ScrollDivTo | None = ...,
        scrollDivUntil: global___ScrollDivUntil | None = ...,
        pageSource: global___PageSource | None = ...,
        refresh: global___Refresh | None = ...,
        select: global___Select | None = ...,
        clearElement: global___ClearElement | None = ...,
        output: global___Output | None = ...,
        findElement: global___FindElement | None = ...,
        keyAction: global___KeyAction | None = ...,
        pressKey: global___PressKey | None = ...,
        sendKeysToActive: global___SendKeysToActive | None = ...,
        uploadFile: global___UploadFile | None = ...,
        downloadFile: global___DownloadFile | None = ...,
        switchWindow: global___SwitchWindow | None = ...,
        closeWindow: global___CloseWindow | None = ...,
        getCurrentURL: global___GetCurrentURL | None = ...,
        setZoom: global___SetZoom | None = ...,
        durationStart: global___DurationStart | None = ...,
        getDuration: global___GetDuration | None = ...,
        getElementScreenshot: global___GetElementScreenshot | None = ...,
        waitForChanges: global___WaitForChanges | None = ...,
        acceptAlert: global___AcceptAlert | None = ...,
        dismissAlert: global___DismissAlert | None = ...,
        checkImageAvailability: global___CheckImageAvailability | None = ...,
        getScreenshot: global___GetScreenshot | None = ...,
        storeElementState: global___StoreElementState | None = ...,
        executeJs: global___ExecuteJS | None = ...,
        executeJsElement: global___ExecuteJSElement | None = ...,
        selectFrame: global___SelectFrame | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["acceptAlert", b"acceptAlert", "action", b"action", "checkImageAvailability", b"checkImageAvailability", "clearElement", b"clearElement", "click", b"click", "closeWindow", b"closeWindow", "dismissAlert", b"dismissAlert", "downloadFile", b"downloadFile", "durationStart", b"durationStart", "executeJs", b"executeJs", "executeJsElement", b"executeJsElement", "findElement", b"findElement", "getCurrentURL", b"getCurrentURL", "getDuration", b"getDuration", "getDynamicTable", b"getDynamicTable", "getElement", b"getElement", "getElementAttribute", b"getElementAttribute", "getElementInnerHtml", b"getElementInnerHtml", "getElementScreenshot", b"getElementScreenshot", "getElementValue", b"getElementValue", "getScreenshot", b"getScreenshot", "keyAction", b"keyAction", "open", b"open", "output", b"output", "pageSource", b"pageSource", "pressKey", b"pressKey", "refresh", b"refresh", "scrollDivTo", b"scrollDivTo", "scrollDivUntil", b"scrollDivUntil", "scrollTo", b"scrollTo", "select", b"select", "selectFrame", b"selectFrame", "sendKeys", b"sendKeys", "sendKeysToActive", b"sendKeysToActive", "setCheckbox", b"setCheckbox", "setZoom", b"setZoom", "storeElementState", b"storeElementState", "switchWindow", b"switchWindow", "uploadFile", b"uploadFile", "wait", b"wait", "waitForChanges", b"waitForChanges", "waitForElement", b"waitForElement", "waitForNew", b"waitForNew"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["acceptAlert", b"acceptAlert", "action", b"action", "checkImageAvailability", b"checkImageAvailability", "clearElement", b"clearElement", "click", b"click", "closeWindow", b"closeWindow", "dismissAlert", b"dismissAlert", "downloadFile", b"downloadFile", "durationStart", b"durationStart", "executeJs", b"executeJs", "executeJsElement", b"executeJsElement", "findElement", b"findElement", "getCurrentURL", b"getCurrentURL", "getDuration", b"getDuration", "getDynamicTable", b"getDynamicTable", "getElement", b"getElement", "getElementAttribute", b"getElementAttribute", "getElementInnerHtml", b"getElementInnerHtml", "getElementScreenshot", b"getElementScreenshot", "getElementValue", b"getElementValue", "getScreenshot", b"getScreenshot", "keyAction", b"keyAction", "open", b"open", "output", b"output", "pageSource", b"pageSource", "pressKey", b"pressKey", "refresh", b"refresh", "scrollDivTo", b"scrollDivTo", "scrollDivUntil", b"scrollDivUntil", "scrollTo", b"scrollTo", "select", b"select", "selectFrame", b"selectFrame", "sendKeys", b"sendKeys", "sendKeysToActive", b"sendKeysToActive", "setCheckbox", b"setCheckbox", "setZoom", b"setZoom", "storeElementState", b"storeElementState", "switchWindow", b"switchWindow", "uploadFile", b"uploadFile", "wait", b"wait", "waitForChanges", b"waitForChanges", "waitForElement", b"waitForElement", "waitForNew", b"waitForNew"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["action", b"action"]) -> typing_extensions.Literal["open", "click", "setCheckbox", "sendKeys", "waitForElement", "waitForNew", "wait", "getElement", "getElementInnerHtml", "getElementValue", "getElementAttribute", "getDynamicTable", "scrollTo", "scrollDivTo", "scrollDivUntil", "pageSource", "refresh", "select", "clearElement", "output", "findElement", "keyAction", "pressKey", "sendKeysToActive", "uploadFile", "downloadFile", "switchWindow", "closeWindow", "getCurrentURL", "setZoom", "durationStart", "getDuration", "getElementScreenshot", "waitForChanges", "acceptAlert", "dismissAlert", "checkImageAvailability", "getScreenshot", "storeElementState", "executeJs", "executeJsElement", "selectFrame"] | None: ...

global___RhWebActions = RhWebActions
