
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-04-04T22:04:57+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "a9966596240ee8ff8078c055ffc954141aef496c",
 "version": "8.10.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
