
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-04-08T10:19:04-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "4695985a49cb12ec6733fb69a2a24f19283cf997",
 "version": "2024.4.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
