import os

DEFAULT_PAGE_SIZE = int(os.getenv('DISCOVERY_DEFAULT_PAGE_SIZE') or 100)
DEFAULT_OFFSET = 0

DESC = 'desc'
ASC = 'asc'

DISCOVERY_GRAPHQL_URL = 'DISCOVERY_GRAPHQL_URL'
ENABLE_DISCOVERY_RETRIES = 'ENABLE_DISCOVERY_RETRIES'
