# coding: utf-8

"""
    Dti.TaxCore.VSDC.Api

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import dti_tax_core_vsdc_api_client_swagger
from dti_tax_core_vsdc_api_client_swagger.models.tax_rate_group import TaxRateGroup  # noqa: E501
from dti_tax_core_vsdc_api_client_swagger.rest import ApiException


class TestTaxRateGroup(unittest.TestCase):
    """TaxRateGroup unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTaxRateGroup(self):
        """Test TaxRateGroup"""
        # FIXME: construct object with mandatory attributes with example values
        # model = dti_tax_core_vsdc_api_client_swagger.models.tax_rate_group.TaxRateGroup()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
