# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_cons.ipynb.

# %% auto 0
__all__ = ['AXES_ASCII']

# %% ../nbs/00_cons.ipynb 6
import string

# %% ../nbs/00_cons.ipynb 8
#| export

# %% ../nbs/00_cons.ipynb 11
#| export

# %% ../nbs/00_cons.ipynb 13
#| export


# %% ../nbs/00_cons.ipynb 15
#| export


# %% ../nbs/00_cons.ipynb 17
#| export


# %% ../nbs/00_cons.ipynb 19
from putl import shiftcycle

# %% ../nbs/00_cons.ipynb 21
#| export


# %% ../nbs/00_cons.ipynb 23
AXES_ASCII = ''.join(shiftcycle('x', string.ascii_lowercase))
'''The alphabet string, cycled to start at x i.e. `'xyzabcdefghijklmnopqrstuvw'`.''';

# %% ../nbs/00_cons.ipynb 25
#| export
