
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-04-08T17:52:31-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "05868fde49af9dc348c8117f9c129eef39c2f0d2",
 "version": "0.2.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
