# coding: utf-8

"""
    CryptoAPIs

    Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.

    The version of the OpenAPI document: 2023-04-25
    Contact: developers@cryptoapis.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from com.cryptoapis.rest_apis.sdk.models.create_single_transaction_request_from_address_without_fee_priority_ri_recipient_inner import CreateSingleTransactionRequestFromAddressWithoutFeePriorityRIRecipientInner
from com.cryptoapis.rest_apis.sdk.models.create_single_transaction_request_from_address_without_fee_priority_ri_sender import CreateSingleTransactionRequestFromAddressWithoutFeePriorityRISender
from com.cryptoapis.rest_apis.sdk.models.create_single_transaction_request_from_address_without_fee_priority_ri_total_amount import CreateSingleTransactionRequestFromAddressWithoutFeePriorityRITotalAmount
from typing import Optional, Set
from typing_extensions import Self

class CreateSingleTransactionRequestFromAddressWithoutFeePriorityRI(BaseModel):
    """
    CreateSingleTransactionRequestFromAddressWithoutFeePriorityRI
    """ # noqa: E501
    callback_secret_key: Optional[StrictStr] = Field(default=None, description="Represents the Secret Key value provided by the customer. This field is used for security purposes during the callback notification, in order to prove the sender of the callback as Crypto APIs. For more information please see our [Documentation](https://developers.cryptoapis.io/technical-documentation/general-information/callbacks#callback-security).", alias="callbackSecretKey")
    callback_url: Optional[StrictStr] = Field(default=None, description="Represents the URL that is set by the customer where the callback will be received at. The callback notification will be received only if and when the event occurs. `We support ONLY httpS type of protocol`.", alias="callbackUrl")
    classic_address: Optional[StrictStr] = Field(default=None, description="Represents the public address, which is a compressed and shortened form of a public key. The classic address is shown when the source address is an x-Address.", alias="classicAddress")
    note: Optional[StrictStr] = Field(default=None, description="Represents an optional note to add a free text in, explaining or providing additional detail on the transaction request.")
    recipient: List[CreateSingleTransactionRequestFromAddressWithoutFeePriorityRIRecipientInner] = Field(description="Defines the destination for the transaction, i.e. the recipient(s).")
    sender: CreateSingleTransactionRequestFromAddressWithoutFeePriorityRISender
    transaction_request_id: StrictStr = Field(description="Represents a unique identifier of the transaction request (the request sent to make a transaction), which helps in identifying which callback and which `referenceId` concern that specific transaction request.", alias="transactionRequestId")
    transaction_request_status: StrictStr = Field(description="Defines the status of the transaction, e.g. \"created, \"await_approval\", \"pending\", \"prepared\", \"signed\", \"broadcasted\", \"success\", \"failed\", \"rejected\", mined\".", alias="transactionRequestStatus")
    total_amount: Optional[CreateSingleTransactionRequestFromAddressWithoutFeePriorityRITotalAmount] = Field(default=None, alias="totalAmount")
    __properties: ClassVar[List[str]] = ["callbackSecretKey", "callbackUrl", "classicAddress", "note", "recipient", "sender", "transactionRequestId", "transactionRequestStatus", "totalAmount"]

    @field_validator('transaction_request_status')
    def transaction_request_status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['created', 'await-approval', 'pending', 'prepared', 'signed', 'broadcasted', 'success', 'failed', 'rejected', 'mined', 'mined-with-errors']):
            raise ValueError("must be one of enum values ('created', 'await-approval', 'pending', 'prepared', 'signed', 'broadcasted', 'success', 'failed', 'rejected', 'mined', 'mined-with-errors')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateSingleTransactionRequestFromAddressWithoutFeePriorityRI from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in recipient (list)
        _items = []
        if self.recipient:
            for _item in self.recipient:
                if _item:
                    _items.append(_item.to_dict())
            _dict['recipient'] = _items
        # override the default output from pydantic by calling `to_dict()` of sender
        if self.sender:
            _dict['sender'] = self.sender.to_dict()
        # override the default output from pydantic by calling `to_dict()` of total_amount
        if self.total_amount:
            _dict['totalAmount'] = self.total_amount.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateSingleTransactionRequestFromAddressWithoutFeePriorityRI from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "callbackSecretKey": obj.get("callbackSecretKey"),
            "callbackUrl": obj.get("callbackUrl"),
            "classicAddress": obj.get("classicAddress"),
            "note": obj.get("note"),
            "recipient": [CreateSingleTransactionRequestFromAddressWithoutFeePriorityRIRecipientInner.from_dict(_item) for _item in obj["recipient"]] if obj.get("recipient") is not None else None,
            "sender": CreateSingleTransactionRequestFromAddressWithoutFeePriorityRISender.from_dict(obj["sender"]) if obj.get("sender") is not None else None,
            "transactionRequestId": obj.get("transactionRequestId"),
            "transactionRequestStatus": obj.get("transactionRequestStatus"),
            "totalAmount": CreateSingleTransactionRequestFromAddressWithoutFeePriorityRITotalAmount.from_dict(obj["totalAmount"]) if obj.get("totalAmount") is not None else None
        })
        return _obj


