# coding: utf-8

"""
    CryptoAPIs

    Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.

    The version of the OpenAPI document: 2023-04-25
    Contact: developers@cryptoapis.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List
from com.cryptoapis.rest_apis.sdk.models.get_eip1559_fee_recommendations_ri_base_fee_per_gas import GetEIP1559FeeRecommendationsRIBaseFeePerGas
from com.cryptoapis.rest_apis.sdk.models.get_eip1559_fee_recommendations_ri_max_fee_per_gas import GetEIP1559FeeRecommendationsRIMaxFeePerGas
from com.cryptoapis.rest_apis.sdk.models.get_eip1559_fee_recommendations_ri_max_priority_fee_per_gas import GetEIP1559FeeRecommendationsRIMaxPriorityFeePerGas
from typing import Optional, Set
from typing_extensions import Self

class GetEIP1559FeeRecommendationsRI(BaseModel):
    """
    GetEIP1559FeeRecommendationsRI
    """ # noqa: E501
    base_fee_per_gas: GetEIP1559FeeRecommendationsRIBaseFeePerGas = Field(alias="baseFeePerGas")
    max_fee_per_gas: GetEIP1559FeeRecommendationsRIMaxFeePerGas = Field(alias="maxFeePerGas")
    max_priority_fee_per_gas: GetEIP1559FeeRecommendationsRIMaxPriorityFeePerGas = Field(alias="maxPriorityFeePerGas")
    __properties: ClassVar[List[str]] = ["baseFeePerGas", "maxFeePerGas", "maxPriorityFeePerGas"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetEIP1559FeeRecommendationsRI from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of base_fee_per_gas
        if self.base_fee_per_gas:
            _dict['baseFeePerGas'] = self.base_fee_per_gas.to_dict()
        # override the default output from pydantic by calling `to_dict()` of max_fee_per_gas
        if self.max_fee_per_gas:
            _dict['maxFeePerGas'] = self.max_fee_per_gas.to_dict()
        # override the default output from pydantic by calling `to_dict()` of max_priority_fee_per_gas
        if self.max_priority_fee_per_gas:
            _dict['maxPriorityFeePerGas'] = self.max_priority_fee_per_gas.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetEIP1559FeeRecommendationsRI from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "baseFeePerGas": GetEIP1559FeeRecommendationsRIBaseFeePerGas.from_dict(obj["baseFeePerGas"]) if obj.get("baseFeePerGas") is not None else None,
            "maxFeePerGas": GetEIP1559FeeRecommendationsRIMaxFeePerGas.from_dict(obj["maxFeePerGas"]) if obj.get("maxFeePerGas") is not None else None,
            "maxPriorityFeePerGas": GetEIP1559FeeRecommendationsRIMaxPriorityFeePerGas.from_dict(obj["maxPriorityFeePerGas"]) if obj.get("maxPriorityFeePerGas") is not None else None
        })
        return _obj


