# coding: utf-8

"""
    CryptoAPIs

    Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.

    The version of the OpenAPI document: 2023-04-25
    Contact: developers@cryptoapis.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List
from com.cryptoapis.rest_apis.sdk.models.get_transaction_details_by_transaction_idribsb_vin_inner_script_sig import GetTransactionDetailsByTransactionIDRIBSBVinInnerScriptSig
from typing import Optional, Set
from typing_extensions import Self

class ListUnconfirmedTransactionsByAddressRIBSBCVinInner(BaseModel):
    """
    ListUnconfirmedTransactionsByAddressRIBSBCVinInner
    """ # noqa: E501
    addresses: List[StrictStr]
    script_sig: GetTransactionDetailsByTransactionIDRIBSBVinInnerScriptSig = Field(alias="scriptSig")
    sequence: StrictStr = Field(description="Represents the script sequence number.")
    txid: StrictStr = Field(description="String representation of the txid")
    txinwitness: List[StrictStr]
    value: StrictStr = Field(description="Represents the sent/received amount.")
    vout: StrictInt = Field(description="Defines the vout of the transaction output, i.e. which output to spend.")
    __properties: ClassVar[List[str]] = ["addresses", "scriptSig", "sequence", "txid", "txinwitness", "value", "vout"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ListUnconfirmedTransactionsByAddressRIBSBCVinInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of script_sig
        if self.script_sig:
            _dict['scriptSig'] = self.script_sig.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ListUnconfirmedTransactionsByAddressRIBSBCVinInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "addresses": obj.get("addresses"),
            "scriptSig": GetTransactionDetailsByTransactionIDRIBSBVinInnerScriptSig.from_dict(obj["scriptSig"]) if obj.get("scriptSig") is not None else None,
            "sequence": obj.get("sequence"),
            "txid": obj.get("txid"),
            "txinwitness": obj.get("txinwitness"),
            "value": obj.get("value"),
            "vout": obj.get("vout")
        })
        return _obj


