# Generated by Django 4.0.4 on 2022-05-12 23:39

from django.db import migrations, models

import multisite.models


class Migration(migrations.Migration):
    dependencies = [
        ("multisite", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alias",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="alias",
            name="is_canonical",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Does this domain name match the one in site?",
                validators=[multisite.models.validators.validate_true_or_none],
                verbose_name="is canonical?",
            ),
        ),
    ]
