# Generated by Django 4.2.11 on 2024-03-27 04:14

from django.db import migrations
import multisite.models.managers


class Migration(migrations.Migration):

    dependencies = [
        ("multisite", "0003_alter_alias_options_alter_alias_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="alias",
            managers=[
                ("objects", multisite.models.managers.AliasManager()),
                ("canonical", multisite.models.managers.CanonicalAliasManager()),
                ("aliases", multisite.models.managers.NotCanonicalAliasManager()),
            ],
        ),
    ]
