# Generated by Django 3.0.13 on 2022-07-24 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_invoice_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrival',
            name='currency_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='currency_rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
