# Generated by Django 3.0.13 on 2022-12-05 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0008_totals'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='service_total_card',
            field=models.FloatField(default=0, verbose_name='Credit card'),
        ),
        migrations.AddField(
            model_name='sale',
            name='service_total_cassa',
            field=models.FloatField(default=0, verbose_name='Cassa'),
        ),
        migrations.AddField(
            model_name='sale',
            name='service_total_post',
            field=models.FloatField(default=0, verbose_name='Nova poshta'),
        ),
    ]
