
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-04-05T11:32:20-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "3fafb0b78b389d55e19b26716c5d893b5b8c7990",
 "version": "2.8.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
