
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-04-04T11:52:15+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "78188ae4e7ffb221b0b7f96b61635ea918c13c82",
 "version": "6.25.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
