
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-04-07T02:11:55+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "5b248f6a0dd29cb9c2a9545f980a88de16a6b753",
 "version": "1.4.dev2414"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
