# Generated by Django 4.2.3 on 2023-09-11 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ib_core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagbinder',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='tagbinder',
            name='tag_manager',
        ),
        migrations.AlterField(
            model_name='tagbinder',
            name='key',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
