# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from voiceos.models.call_recording import CallRecording

class TestCallRecording(unittest.TestCase):
    """CallRecording unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CallRecording:
        """Test CallRecording
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CallRecording`
        """
        model = CallRecording()
        if include_optional:
            return CallRecording(
                recording_url = ''
            )
        else:
            return CallRecording(
                recording_url = '',
        )
        """

    def testCallRecording(self):
        """Test CallRecording"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
