# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fooocusapi_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_all_models_v1_engines_all_models_get(self) -> None:
        """Test case for all_models_v1_engines_all_models_get

        All Models
        """
        pass

    def test_all_styles_v1_engines_styles_get(self) -> None:
        """Test case for all_styles_v1_engines_styles_get

        All Styles
        """
        pass

    def test_describe_image_v1_tools_describe_image_post(self) -> None:
        """Test case for describe_image_v1_tools_describe_image_post

        Describe Image
        """
        pass

    def test_get_history_v1_generation_job_history_get(self) -> None:
        """Test case for get_history_v1_generation_job_history_get

        Get History
        """
        pass

    def test_home_get(self) -> None:
        """Test case for home_get

        Home
        """
        pass

    def test_img_inpaint_or_outpaint_v1_generation_image_inpaint_outpaint_post(self) -> None:
        """Test case for img_inpaint_or_outpaint_v1_generation_image_inpaint_outpaint_post

        Img Inpaint Or Outpaint
        """
        pass

    def test_img_inpaint_or_outpaint_v2_v2_generation_image_inpaint_outpaint_post(self) -> None:
        """Test case for img_inpaint_or_outpaint_v2_v2_generation_image_inpaint_outpaint_post

        Img Inpaint Or Outpaint V2
        """
        pass

    def test_img_prompt_v1_generation_image_prompt_post(self) -> None:
        """Test case for img_prompt_v1_generation_image_prompt_post

        Img Prompt
        """
        pass

    def test_img_prompt_v2_generation_image_prompt_post(self) -> None:
        """Test case for img_prompt_v2_generation_image_prompt_post

        Img Prompt
        """
        pass

    def test_img_upscale_or_vary_v1_generation_image_upscale_vary_post(self) -> None:
        """Test case for img_upscale_or_vary_v1_generation_image_upscale_vary_post

        Img Upscale Or Vary
        """
        pass

    def test_img_upscale_or_vary_v2_v2_generation_image_upscale_vary_post(self) -> None:
        """Test case for img_upscale_or_vary_v2_v2_generation_image_upscale_vary_post

        Img Upscale Or Vary V2
        """
        pass

    def test_job_queue_v1_generation_job_queue_get(self) -> None:
        """Test case for job_queue_v1_generation_job_queue_get

        Job Queue
        """
        pass

    def test_ping_ping_get(self) -> None:
        """Test case for ping_ping_get

        Ping
        """
        pass

    def test_query_job_v1_generation_query_job_get(self) -> None:
        """Test case for query_job_v1_generation_query_job_get

        Query Job
        """
        pass

    def test_refresh_models_v1_engines_refresh_models_post(self) -> None:
        """Test case for refresh_models_v1_engines_refresh_models_post

        Refresh Models
        """
        pass

    def test_stop_v1_generation_stop_post(self) -> None:
        """Test case for stop_v1_generation_stop_post

        Stop
        """
        pass

    def test_text2img_generation_v1_generation_text_to_image_post(self) -> None:
        """Test case for text2img_generation_v1_generation_text_to_image_post

        Text2Img Generation
        """
        pass

    def test_text_to_img_with_ip_v2_generation_text_to_image_with_ip_post(self) -> None:
        """Test case for text_to_img_with_ip_v2_generation_text_to_image_with_ip_post

        Text To Img With Ip
        """
        pass


if __name__ == '__main__':
    unittest.main()
