# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fooocusapi_client.models.async_job_stage import AsyncJobStage

class TestAsyncJobStage(unittest.TestCase):
    """AsyncJobStage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAsyncJobStage(self):
        """Test AsyncJobStage"""
        # inst = AsyncJobStage()

if __name__ == '__main__':
    unittest.main()
