
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-04-05T17:39:00+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "0e70789b4e5098586fee0d023cfc0b372a9f5868",
 "version": "0.4.0.post6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
