from . import schema as schema
from _typeshed import Incomplete
from collections.abc import MutableMapping

logger: Incomplete

class ServerInfo(MutableMapping):
    _DIR: str
    def __init__(self, api) -> None: ...
    def __getitem__(self, key): ...
    def __setitem__(self, key, value) -> None: ...
    def __delitem__(self, key) -> None: ...
    def __iter__(self): ...
    def __len__(self): ...
    def update_validity(self, ttl) -> None: ...
    def is_valid(self): ...

def get_package(api): ...
