# Generated by Django 5.0.2 on 2024-03-18 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_pdf', '0006_remove_modelx_model_filed7_modelx_model_filed7'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modela',
            name='modelx',
        ),
        migrations.RemoveField(
            model_name='modelx',
            name='model_filed7',
        ),
        migrations.AddField(
            model_name='modela',
            name='modelx',
            field=models.ManyToManyField(related_name='model_as', to='example_pdf.modelx'),
        ),
        migrations.AddField(
            model_name='modelx',
            name='model_filed7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='example_pdf.modeltype', verbose_name='模型X字段7'),
        ),
    ]
