# Generated by Django 3.0.13 on 2022-06-08 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_tecdoc'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tecdoc_description',
            field=models.TextField(blank=True, editable=False, max_length=10000),
        ),
    ]
