# Generated by Django 3.0.13 on 2022-06-18 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_tecdoc_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tecdoc_description',
        ),
    ]
